### PR TITLE
feat: exit with 101 from forc-test if there are failing tests

### LINKED ISSUE #4462: Exit with different exit status if unit tests fails vs forc-test itself fails
Currently we cannot differentiate between `forc-test` failure and the existence of failing tests from exit status since they both return 1. 

First mentioned here:

https://github.com/FuelLabs/sway/pull/4417#issuecomment-1501829667

We can continue to return 1 if `forc-test` itself fails and return `101` if there are failing unit tests following cargo's footsteps. This should ideally be documented as well.

Since we introduced `ForcResult` in #4455 this should be fairly easy to tackle.

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description
closes #4462.

With this PR we exit from `forc test` with 101 exit status, if there are failing unit tests. If `forc test` execution itself fails we exit with 1. This is useful especially in CIs as the return status can be checked to better understand what is happening. 

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by kayagokalp** [comment]
waiting for #4460 to go in

**Review by JoshuaBatty — APPROVED** [review]

**Comment by sdankel** [comment]
This looks like it should work, but it would be nice to show that this is working by pushing a commit that makes the test fail, so we can see in CI that it's blocking the PR now.

**Review by sdankel — COMMENTED** [review]
This looks like it should work, but it would be nice to show that this is working by pushing a commit that makes the test fail, so we can see in CI that it's blocking the PR now.

**Comment by kayagokalp** [comment]
Hey @sdankel, thanks for the review

> This looks like it should work, but it would be nice to show that this is working by pushing a commit that makes the test fail, so we can see in CI that it's blocking the PR now.

Of course will do that in a second but let me also note that `forc-test` ci is non-blocking issue is fixed in #4417 and you can see that tests were failing and blocking before IR fix from this run. https://github.com/FuelLabs/sway/actions/runs/4654110533/jobs/8235568507.

But I agree it is a good idea to see if returning 101 somehow introduces a regression

**Comment by kayagokalp** [comment]
[Noice](https://www.youtube.com/watch?v=Akwm2UZJ34o&t=22s) looks like it still blocks the CI https://github.com/FuelLabs/sway/actions/runs/4747714342/jobs/8432983691?pr=4463

**Review by sdankel — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
