### PR TITLE
Add function calls to the back end.

### PR DESCRIPTION
**Pull request by otrho**
Probably closes some issues, not sure.  Maybe #1823?

Partially blocked by #2885, but the test which depends has been disabled until it's merged.

**This is huge, I've tried to split each commit up into different areas, so it might be easier to review per commit.**

### Done

Here's most of what we need to have non-inlined function calls in ASM gen.  It introduces a calling convention which resembles any typical ABI, using call frames on the stack, reserved registers for args and dynamic jumps to return, much like `BL` on ARM architectures.

A lot of the work has been in tidying up memory use on the stack, to make sure nothing is leaked and doesn't corrupt the call frames.

The data section has been rewritten to no longer use `Literal`s from the parser and instead has its own very basic values, which are almost untyped.  Just words, byte arrays, or collections of those values are supported.

The IR generation has been tightened up a bit to prevent inconsistent state.

The ASM generation has changed order.  There are 3 stages:
- 'virtual' ops which are abstract in the sense that they use an infinite number of registers, use symbolic labels for control flow and can load values by id from the data section.
- 'realised' ops which still use infinite registers but have the labels converted to concrete addresses for control flow, and the data section has explicit storage and addressing.
- 'allocated' ops which have been through register allocation, using only those registers actually available in the VM.

Prior to this change it went 'virtual' -> 'realised' -> 'allocated'.

Register allocation needs to be per function though and after address realisation it's no longer possible to add or remove instructions.  A part of setting up a call frame is to store any registers used in the function to the stack and to restore them before returning, to avoid corrupting values in the caller.  Which registers are used and therefore need to be preserved is unknown until after register allocation, and the act of preserving those registers involves inserting new `STORE` and `LOAD` instructions which must be done before address realisation.

So, we now do 'virtual' -> 'allocated' -> 'realised'.  This meant changing `asm_lang` and `asm_generation` quite a bit.

### To Do

- We still can't make calls to functions with more than 6 args, as they will need to be passed on the stack.
- We still can't make calls to functions which return a reference-type value, as it will also need to be passed (back) on the stack.

For both these cases we still force inlining of those calls.  This was done only due to the desire to get this change in sooner rather than later, and can be addressed in follow-up PRs.

- `asm_lang` is a bit of a mess.  It has been hacked upon to make the changes needed for the new pipeline order, but it needs to be redesigned and to have much of the redundancy removed.
- `asm_generation` is a bit of a mess.  It still needs to be refactored, as what used to be in `from_ir.rs` is now still mostly in `asm_builder.rs`.
- Memory management and handling of aggregates is still a warty part of this code, but I've been complaining about this for ages and aim to clean it up pronto.
- `sway_ir` has had a very open interface and this needs to be locked down some more.  It has grown very organically as needed by the compiler, but it's starting to show some cracks and needs work to straighten it out with a nice consistent API.
- The `inline` pass in `sway-ir` could be tuned, its heuristic is currently just using some parameters I thought would work OK.
- `--print-intermediate-asm` will print the ASM twice at the moment, before and after allocation.  I think we need a 'preliminary' asm output flag so we can see it at each stage.

- https://github.com/FuelLabs/sway/issues/2904
- https://github.com/FuelLabs/sway/issues/2905
- https://github.com/FuelLabs/sway/issues/2505
- https://github.com/FuelLabs/sway/issues/2906
- https://github.com/FuelLabs/sway/issues/2819
- https://github.com/FuelLabs/sway/issues/2907

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
>  we now do 'virtual' -> 'allocated' -> 'realised'. 

I do like that, assuming there are no performance implications. It's nice not to have to worry about jumps labels like I was previously doing in the register allocator. I see you've removed that now which is great.

**Review by mohammadfawaz — APPROVED** [review]
Can't say I understand every line of code in here, but the overall approach and the changes to the assembly all look good to me. Approving given that tests seem to pass. Did you get a chance to test this PR in the Sway applications repo?

**Comment by otrho** [comment]
> Approving given that tests seem to pass. Did you get a chance to test this PR in the Sway applications repo?

Ahh, I did not, yet.  Will take a look over the weekend.

**Comment by mohammadfawaz** [comment]
We still can't make calls to functions which return a reference-type value

> Sigh, not extraordinary, though these apps are pretty small.

I bet a lot of the functions being called are either too small or return reference types. It'll be interesting to get a count of how many functions are actually *not* inlined per-application.

**Comment by otrho** [comment]
True, let's not get ahead of ourselves.  Need to re-assess after #2905 goes in.

**Comment by vaivaswatha** [comment]
Echoing @mohammadfawaz 's  words, I haven't looked at every detail, but overall this seems ok.

**Review by vaivaswatha — DISMISSED** [review]

**Review by vaivaswatha — APPROVED** [review]

**Review by mohammadfawaz — APPROVED** [review]

**Pull request merged**
