### PR TITLE
Disallow assigning to fields of non-mutable structs

### LINKED ISSUE #908: The compiler does not prevent assigning a data member of a non-mutable struct
Here's a simple example. The code compiles and the `assert` passes. I'm not supposed to be able to write to `S.x` here since `S` is not declared as mutable.
```rust
script;
use std::chain::*;

struct S { x: u64 }

fn main() {
    let s = S { x: 0 }; // Non-mutable!!
    s.x = 1;
    assert(s.x == 1);
}
```
Reassigning the whole struct causes an error but reassigning parts of it does not.

### PR DESCRIPTION
**Pull request by canndrew**
Fixes #908

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Thanks Andrew! There seems to be some E2E tests failing. 

Have you also checked if the test I have here passes? https://github.com/FuelLabs/sway/issues/908#issuecomment-1091883879 - I think there's a similar one in our tests.

**Review by adlerjohn — COMMENTED** [review]
failing CI

**Comment by mohammadfawaz** [comment]
I believe the failing E2E test requires the `mut` keyword on function arguments which we don't have yet. Otherwise, the test will continue to fail with your change. We can either wait until `mut` for arguments is fully implemented before submitting this change, or disable the test for now and mark it as blocked by the "`mut` keyword for arguments" feature.

Either way, I'm going to convert this to a draft to reduce the number of PRs that are ready for review. I hope you don't mind!

**Comment by canndrew** [comment]
@mohammadfawaz: This is the test case that's failing.

```
script;

use std::assert::assert;

struct A {
    a: u64,
    b: u64,
}

impl A {
    fn f(self) {
        self.a = 42;
        self.b = 77;
    }
}

fn main() -> bool {
    let a = A {
        a: 0,
        b: 0,
    };
    a.f();
    assert(a.a == 42);
    assert(a.b == 77);
    true
}
```

The problem here isn't the lack of `mut` on function parameters, it's that the code here doesn't make sense. Assuming that sway is meant to have rust-like semantics rather than java-like semantics then the method `f` moves (or copies) `a` and so any modifications that `f` makes to `self` still won't show-up in `main`. In order to make this work we need `&mut self` methods, but references aren't implemented at all yet.

If this test passed before without the `mut`-check then that's a bad thing. The only way to make something like this work with mutable references is to re-write the code like this:

```
script;

use std::assert::assert;

struct A {
    a: u64,
    b: u64,
}

impl A {
    fn f(mut self) -> A {
        self.a = 42;
        self.b = 77;
        self                // <- return self here
    }
}

fn main() -> bool {
    let a = A {
        a: 0,
        b: 0,
    };
    let a = a.f();          // <- rebind `a` here
    assert(a.a == 42);
    assert(a.b == 77);
    true
}
```

@adlerjohn ^^

**Comment by mohammadfawaz** [comment]
> @mohammadfawaz: This is the test case that's failing.
> 
> 
> 
> ```
> 
> script;
> 
> 
> 
> use std::assert::assert;
> 
> 
> 
> struct A {
> 
>     a: u64,
> 
>     b: u64,
> 
> }
> 
> 
> 
> impl A {
> 
>     fn f(self) {
> 
>         self.a = 42;
> 
>         self.b = 77;
> 
>     }
> 
> }
> 
> 
> 
> fn main() -> bool {
> 
>     let a = A {
> 
>         a: 0,
> 
>         b: 0,
> 
>     };
> 
>     a.f();
> 
>     assert(a.a == 42);
> 
>     assert(a.b == 77);
> 
>     true
> 
> }
> 
> ```
> 
> 
> 
> The problem here isn't the lack of `mut` on function parameters, it's that the code here doesn't make sense. Assuming that sway is meant to have rust-like semantics rather than java-like semantics then the method `f` moves (or copies) `a` and so any modifications that `f` makes to `self` still won't show-up in `main`. In order to make this work we need `&mut self` methods, but references aren't implemented at all yet.
> 
> 
> 
> If this test passed before without the `mut`-check then that's a bad thing. The only way to make something like this work without mutable references is to re-write the code like this:
> 
> 
> 
> ```
> 
> script;
> 
> 
> 
> use std::assert::assert;
> 
> 
> 
> struct A {
> 
>     a: u64,
> 
>     b: u64,
> 
> }
> 
> 
> 
> impl A {
> 
>     fn f(mut self) -> A {
> 
>         self.a = 42;
> 
>         self.b = 77;
> 
>         self                // <- return self here
> 
>     }
> 
> }
> 
> 
> 
> fn main() -> bool {
> 
>     let a = A {
> 
>         a: 0,
> 
>         b: 0,
> 
>     };
> 
>     let a = a.f();          // <- rebind `a` here
> 
>     assert(a.a == 42);
> 
>     assert(a.b == 77);
> 
>     true
> 
> }
> 
> ```
> 
> 
> 
> @adlerjohn ^^

You're absolutely right. That makes a lot of sense and this is where #1188 comes in. The failing test is indeed broken because it needs mut refs (or mut + ret like you wrote in the second example). Given this, I suggest we disable the test for now and track re-enabling it in #1188. The fix in this PR is more critical to merge I think.

**Comment by canndrew** [comment]
I've disabled to offending test by commenting it out with a note linking to this issue. Is this good to go now?

**Review by adlerjohn — COMMENTED** [review]
CI failing still ❗

**Comment by mohammadfawaz** [comment]
Ah yes.. this test should probably be removed as well: https://github.com/FuelLabs/sway/blob/master/sway-core/tests/sway_to_ir/impl_self_reassignment.sw

There's probably no clean way to disable it atm, so we will just have to delete it for the time being.

**Review by mohammadfawaz — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
