### PR TITLE
Add support for `package` field under `dependencies`. If unspecified, require that dependency name matches package name.

### LINKED ISSUE #977: Either require that dependency name matches project name, or add a `package` field like cargo to support aliases
I'm currently implementing #952 and noticed that currently we don't require that the names of declared dependencies match the project name of the dependency. For example, `std` is always declared with the name `std` in the dependency list, however its `Forc.toml`'s `[project]` name is `lib-std`.

In a way, not having this requirement is convenient for easily aliasing packages in the case that the source points to a single package, however in order to implement #952 we need to be able to inspect `Manifest`s for a particular name while searching in order to find the specified dependencies, otherwise there is some ambiguity in the case that a repo contains multiple packages.

Cargo works by requiring that the dependency name matches the manifest-declared package name by default. So in the following, the repo must contain a `Cargo.toml` with the package name "foo"

```toml
foo = { git = "https://github.com/owner/repo", branch = "main" }
```

However, cargo does allow using a different name on the left-hand side as long as the `package` field is specified like so:

```toml
foo-alt = { git = "https://github.com/owner/repo", branch = "main", package = "foo" }
```

I propose we take the same approach!

### PR DESCRIPTION
**Pull request by mitchmindtree**
Closes #977 - see that issue for motivation. Unblocks #978.

A new `should_pass/forc/dependency_package_field` test has been added that tests the functionality.

All tests that depend on `std` and are pinned to a `sway-lib-std` commit older than https://github.com/FuelLabs/sway-lib-std/commit/385c45738b026958a0fbd2903998c115cb9551eb have been updated to the latest commit.

### CODE REVIEW

**Review by adlerjohn — DISMISSED** [review]
utACK

**Review by JoshuaBatty — DISMISSED** [review]
Nice, looks good to me. The test runs successfully on my end. just some conflicts with the master branch that need resolving.

**Comment by mitchmindtree** [comment]
Okydoke, fixed the test conflicts, should be good to go :green_circle:

**Review by JoshuaBatty — APPROVED** [review]
ship it

**Pull request merged**
