### PR TITLE
clippy doesn't fail on warnings

### PR DESCRIPTION
**Pull request by eureka-cpu**

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
It's expected that Clippy CI now fails, right?

**Comment by eureka-cpu** [comment]
> It's expected that Clippy CI now fails, right?

Yes, if there are warnings it should fail. Just waiting on Alex to verify that it's failing _correctly_.

**Comment by adlerjohn** [comment]
task failed successfully

**Review by sezna — CHANGES_REQUESTED** [review]
This is exactly what we need -- can you remove those two clones so this passes, and we'll merge it in? Thanks!

**Review by sezna — APPROVED** [review]

**Pull request merged**
