### PR TITLE
Embed Fuel-Core docker image within CI

### PR DESCRIPTION
**Pull request by ellioty**

### CODE REVIEW

**Comment by adlerjohn** [comment]
FYI, in the future you don't have to change `master` to your branch for things that are supposed to run in a branch too. The flag `pull_request:` means it runs on every push to a PR. Changing `master` to your branch is for things _that are supposed to only run on master_.

**Comment by ellioty** [comment]
Understood, I'll create a PR and test it out that way instead of changing the branch directly in the future

**Comment by Voxelot** [comment]
How do we configure the image tag to pull? Maybe we could put the tag into a .env file somewhere in the .github dir?

**Comment by adlerjohn** [comment]
Yeah, we should 100% have the version of `fuel-core` set, instead of always using `latest`. There's no guarantee `fuel-core` won't have a breaking release and we don't want it affecting downstream CI.

**Comment by ellioty** [comment]
Unfortunately pulling the image from an env variable isn't supported at the moment: https://github.com/github/feedback/discussions/5057

For now, I've just appended the most current release of fuel-core to the image field

**Review by sezna — APPROVED** [review]
LGTM! Thanks for setting this up

**Pull request merged**
