### PR TITLE
Forc deploy docs update

### PR DESCRIPTION
**Pull request by binggh**
Fixes https://github.com/FuelLabs/fuels-rs/issues/216

Instead of having an example of how to deploy using the Rust SDK within the Sway book, we link it to the [page on deploying contracts in the fuels-rs book instead](https://fuellabs.github.io/fuels-rs/latest/getting-started/basics.html#deploying-a-sway-contract), so that only the fuels-rs book has to be updated in future.

### CODE REVIEW

**Review by mitchmindtree — APPROVED** [review]
Nice. LGTM!

**Review by mohammadfawaz — APPROVED** [review]
LGTM!

**Comment by SilentCicero** [comment]
@binggh it's ready :)

**Comment by binggh** [comment]
@SilentCicero i do not have write access 😅

**Pull request merged**
