### PR TITLE
Bump to v0.44.2

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description
Waiting for:

1. #4974
2. #4961

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
would love for #4961 to make it in this release also.

**Comment by sdankel** [comment]
Just curious, do we have a script that bumps the version, or is this done manually?

**Comment by kayagokalp** [comment]
Let's wait confirmation from @IGI-111 before merging this

**Comment by kayagokalp** [comment]
> Just curious, do we have a script that bumps the version, or is this done manually?

This is currently done manually with search and replace.

**Comment by kayagokalp** [comment]
Looks like this should be a major release.

**Pull request closed without merging**
