### PR TITLE
Bugfix in rsh method for b256

### LINKED ISSUE #2288: Right shift operation for b256 bug
sway-lib-core/src/ops.sw 
line 598

### PR DESCRIPTION
**Pull request by nfurfaro**
Fixes a bug in the `rsh` method of the Shiftable trait implementation for `b256` in `core::ops`.
closes #2288

### CODE REVIEW

**Review by adlerjohn — DISMISSED** [review]
utACK

**Review by mohammadfawaz — DISMISSED** [review]

**Comment by otrho** [comment]
Is there a test that used to fail that this change definitely fixes?

**Comment by adlerjohn** [comment]
Good point, a test that exercises the line of code would be good to have.

**Comment by nfurfaro** [comment]
Added a new passing test that fails if I revert the change made to `rsh`.

**Review by otrho — APPROVED** [review]

**Pull request merged**
