### PR TITLE
Switch the IR unit tests to use FileCheck.

### PR DESCRIPTION
**Pull request by otrho**
This is both simpler and a more expressive way to test IR passes.  It uses special embedded directives to confirm that an IR transformation has been applied correctly.

I've had this branch languishing around for a few weeks, thought I'd finish it up and submit it.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Can we also address this now https://github.com/FuelLabs/sway/issues/1206? 😁

**Comment by otrho** [comment]
Yep, once someone approves this one!

**Review by mohammadfawaz — APPROVED** [review]
Very nice! 
Can we somehow ask for specific passes to run in a given test like `llvm-lit` instead of having the pass be part of the test name?

**Comment by otrho** [comment]
Yeah, one day. :)  One step at a time.  Considering there are currently a total of 2 passes, this will do for now.  Thanks.

**Pull request merged**
