### PR TITLE
Rename input_owner to input_coin_owner

### LINKED ISSUE #5029: Rename `input_owner` to `input_coin_owner`
The following function is misleading in its name because it implies that it will get the "owner" of whatever the input is.
In reality, it will only do so if it is a coin.

There are other functions which return; say, the sender / recipient of a message and they are aptly named `input_message_sender` and `input_message_recipient`.

The function and doc comment should be updated to reflect this.
We already have another function which is higher level that returns the owner of all inputs `inputs_owner` (although at the time of writing this a bug is being fixed in that function).

https://github.com/FuelLabs/sway/blob/6478bf6ab8b3b19910a792c5fc4c13ffdc59510b/sway-lib-std/src/inputs.sw#L196-L221

### PR DESCRIPTION
**Pull request by richardgreg**
close #5029

## Description
Changes the misleading name `input_owner` to `input_coin_owner`

Requesting a review and addition of the `Breaking` tag from @Braqzen 

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by Braqzen — DISMISSED** [review]
Changes themselves look fine, thanks

**Comment by Braqzen** [comment]
The `std` tests are failing and they need to be fixed before merging

**Comment by richardgreg** [comment]
Hi @Braqzen, do you know of a command I can use to run a specific test function such as `can_get_input_message_sender` which is failing? I tried something like `cargo run --bin test can_get_input_message_sender` but no tests were run.

If have an idea why `can_get_input_message_sender` in `test/src/sdk-harness/test_projects/tx_fields/mod.rs` fails can just let me know so I make the fix 🙂

**Comment by Braqzen** [comment]
> Hi @Braqzen, do you know of a command I can use to run a specific test function such as `can_get_input_message_sender` which is failing? I tried something like `cargo run --bin test can_get_input_message_sender` but no tests were run.
> 
> If have an idea why `can_get_input_message_sender` in `test/src/sdk-harness/test_projects/tx_fields/mod.rs` fails can just let me know so I make the fix 🙂

1) Build the local sway repository to use the changes that you have made. In the root of the repository run

```bash
cargo build
```

2) Build the sway projects from the root of the repository so that all tests can run

```bash
cargo run --bin=forc build --path test/src/sdk-harness
```

3) Change into the following directory

```bash
cd ./test/src/sdk-harness/test_projects/tx_fields
```

4) Run the test that you want

```bash
cargo test inputs::success::message::can_get_input_message_sender
```

**Comment by omiaydin1** [comment]
very good

**Comment by richardgreg** [comment]
Everything looks good now. Weird that the same implementation failed previously.

Just to be certain, I wanted to run a test on my machine following the instructions you provided, but it throws an error
Screenshot 2023-11-30 at 18 14 18
I'm still getting familiar with Rust and Fuel so I'm not certain 😅. Maybe it's related to `fuel-core run` not working on my machine. I made a [post](https://forum.fuel.network/t/fuel-core-run-fails-to-start/3743) in the forum and I was told that it's a common issue.


Anyway, If it's alright for merging I can rebase it.

**Review by Braqzen — APPROVED** [review]
Ping pong!

**Review by bitzoic — APPROVED** [review]

**Pull request merged**
