### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by sezna**

### CODE REVIEW

**Review by Voxelot — DISMISSED** [review]

**Comment by adlerjohn** [comment]
Should this not be v0.4.0? Are there no breaking changes since v0.3.3?

**Comment by sezna** [comment]
Are there any in particular you think would be breaking?
image

**Comment by adlerjohn** [comment]
Bump fuel-tx is a breaking change

**Comment by mohammadfawaz** [comment]
> Are there any in particular you think would be breaking? image

When you write the changelog, you look at the [commit history](https://github.com/FuelLabs/sway/commits/master) (and grab everything after "bump to v0.3.3") not this list, right?

**Comment by adlerjohn** [comment]
Yes, looking at the default-sorted list of PRs is really inaccurate.

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
