### PR TITLE
Add --log-level and --silent to forc

### PR DESCRIPTION
**Pull request by sdankel**
Closes https://github.com/FuelLabs/sway/issues/2375 https://github.com/FuelLabs/sway/issues/2362

Related https://github.com/FuelLabs/sway/pull/2798

image

1. adds a global `--log-level` option.

2. changes "forc completions --shell" short form from "-s" to "-S" because "-s" is now globally the short form of "--silent"

image

3. similarly, changes "forc addr2line --search-dir" short from from  "-s" to "-S"

image

4. adds a global `--silent` option to all forc commands and renames the old silent mode to "terse mode". 

What used to be called silent mode was not really silent; it would still output 1 line if there were warnings or errors during the build (for example, during CI runs). 
 
There is still a need for a non-global option for terse mode because the test harness runs the build commands directly (without the CLI), so there's no way to pass the global options into the command (for example, `forc::test::forc_check::check` which takes a `forc::cli::CheckCommand` argument).

image

I can't simply set the log level to "ERROR" for the test harness (effectively like a terse mode) because it would be applied to all tests running in that thread, and some of the tests depend on the INFO output to stdout to determine if the test passed. To have separate log levels for `ir_generation` and `e2e_vm_tests`, we'd have to separate those into separate build steps.

### CODE REVIEW

**Review by kayagokalp — APPROVED** [review]
Looks cool to me! One minor discussion point:

 I wonder if changes to `forc-client` should be done to it's own dedicated repo as `forc-client` from sway repo is about to be depreciated 🤔  Maybe @bingcicle can have a better input for that.

**Review by JoshuaBatty — APPROVED** [review]
Nice work @sdankel ! Also cc'ing @bingcicle for his thoughts on migrating the forc-client changes over to the new repo.

**Comment by bingcicle** [comment]
^ sorry I missed this but yeah, the changes to `forc-client` should definitely be in the [new repo](https://github.com/FuelLabs/forc-client) instead

**Comment by JoshuaBatty** [comment]
@sdankel would you mind porting these `forc-client` changes to the new repo in a separate PR? Thanks

**Pull request merged**
