### PR TITLE
Adds better formatting to `match_branch_kind`

### PR DESCRIPTION
**Pull request by eureka-cpu**
This makes some changes to `CodeBlockContents` handling as well as `ItemFn` regarding new line handling, as well as indentation level for `MatchBranchKind`.

### CODE REVIEW

**Comment by kayagokalp** [comment]
closes #2540.

**Review by kayagokalp — APPROVED** [review]
lgtm

**Comment by kayagokalp** [comment]
created the related issue just for documentation purposes, looks really nice thanks for the quick fix!

**Review by Braqzen — APPROVED** [review]
Tentatively approving :)

**Pull request merged**
