### PR TITLE
Adds formatting for long conditional statements

### PR DESCRIPTION
**Pull request by eureka-cpu**
As an added bonus, it also formats small ones too!

Ref #2493

### CODE REVIEW

**Comment by eureka-cpu** [comment]
I've noticed an issue with this so I've converted to draft

**Comment by eureka-cpu** [comment]
Just an update that the extra functionality I've added here will not work properly until we add better handling for indentation tracking

**Comment by eureka-cpu** [comment]
Found another bug, converting to draft while I figure it out

**Review by mitchmindtree — APPROVED** [review]
:shipit:

**Review by kayagokalp — COMMENTED** [review]
🚀

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
