### PR TITLE
Fixes issue with multiline collections formatting.

### PR DESCRIPTION
**Pull request by esdrubal**
Fixes issue #3014.

The following code ...
```
let x = (
    "hello",
    "world",
);
```
... was formatted into:
```
let x = ("hello", "world", );
```
After the fix it is formatted into:
```
let x = ("hello", "world");
```

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Thanks! @eureka-cpu should probably review this as well.

**Comment by kayagokalp** [comment]
Hey @mohammadfawaz, @eureka-cpu is OOO, not sure if he is going to be able to look at this so @bingcicle passed this my way. I am also familiar these parts of the code and planning to have a look at this shortly 👍

**Comment by mohammadfawaz** [comment]
> Hey @mohammadfawaz, @eureka-cpu is OOO, not sure if he is going to be able to look at this so @bingcicle passed this my way. I am also familiar these parts of the code and planning to have a look at this shortly 👍

Fantastic. Thank you @kayagokalp :)

**Review by kayagokalp — APPROVED** [review]
LGTM :) Thanks for the PR

**Pull request merged**
