### PR TITLE
Error on multiple function definitions

### LINKED ISSUE #751: Compiler should error out when the same function is defined multiple times
Example:
```
script;
fn foo() {}
fn foo() {}
fn main() {}
```
Even this should error out:
```
script;
fn foo() {}
fn foo<T>() {}
fn main() {}
```

### PR DESCRIPTION
**Pull request by vaivaswatha**
Closes #751

### CODE REVIEW

**Comment by otrho** [comment]
Looks good!  I'm thinking it might be an idea to create a `should_pass` test which puts the same named function into very close but distinct scopes.  Like putting one in a local library with `dep` & `use`, and `main.sw`, or nested functions (although I'm not sure if Sway supports nested functions yet), or in an ABI or `impl` and global scope.

**Comment by vaivaswatha** [comment]
> Looks good! I'm thinking it might be an idea to create a `should_pass` test which puts the same named function into very close but distinct scopes. Like putting one in a local library with `dep` & `use`, and `main.sw`, or nested functions (although I'm not sure if Sway supports nested functions yet), or in an ABI or `impl` and global scope.

:+1: I'll do that.

**Comment by vaivaswatha** [comment]
> Looks good! I'm thinking it might be an idea to create a `should_pass` test which puts the same named function into very close but distinct scopes. Like putting one in a local library with `dep` & `use`, and `main.sw`, or nested functions (although I'm not sure if Sway supports nested functions yet), or in an ABI or `impl` and global scope.

Thanks @otrho . I've added this now.

**Review by emilyaherbert — CHANGES_REQUESTED** [review]
Awesome job 👍  can you add a test case where the contract imports a function? So something like:

```rust
contract;

dep testlib::foo;

abi TestContr {
    fn foo();
}

fn foo() {}

impl TestContr for Contract {
    fn foo() {
       foo();
    }
}

fn main() {

}
```

**Comment by vaivaswatha** [comment]
> Awesome job +1 can you add a test case where the contract imports a function? So something like:
> 
> ```rust
> contract;
> 
> dep testlib::foo;
> 
> abi TestContr {
>     fn foo();
> }
> 
> fn foo() {}
> 
> impl TestContr for Contract {
>     fn foo() {
>        foo();
>     }
> }
> 
> fn main() {
> 
> }
> ```

Thank you @emilyaherbert . 
> `dep testlib::foo;`

:arrow_up:  didn't work, but :arrow_down: did, so I added that.
```
dep testlib;
use testlib::foo
```

**Review by otrho — APPROVED** [review]

**Comment by mohammadfawaz** [comment]
Merge conflicts! Looks good otherwise :)

**Review by mohammadfawaz — CHANGES_REQUESTED** [review]
The change looks great! Just a small nit on the tests.

**Comment by emilyaherbert** [comment]
> starting to wonder if we should refactor this file so it gets less conflicts, haha. Not sure how we'd do that, though.

Instead of comparing the result of the test in the `mod.rs` file, we could compare it to the contents of a different file. Then we could just blindly iterate through the contents of the test dir. This is similar to how the JSON ABI output is tested: https://github.com/FuelLabs/sway/blob/e8f10e7d66118e2dcc8f0fdcef5ecf3c4a30c830/test/src/e2e_vm_tests/harness.rs#L125

**Comment by vaivaswatha** [comment]
All suggested changes done.

**Comment by otrho** [comment]
> Instead of comparing the result of the test in the `mod.rs` file, we could compare it to the contents of a different file.

This is exactly what I proposed months ago in #723 @emilyaherbert and as `DEITY` is my witness I'm going to start working on it.  These conflicts are just too annoying.

**Review by mohammadfawaz — APPROVED** [review]

**Comment by emilyaherbert** [comment]
> This is exactly what I proposed months ago in https://github.com/FuelLabs/sway/issues/723

Great proposal! I am in favor of doing this 😄

**Comment by mohammadfawaz** [comment]
@emilyaherbert I think this needs your approval to go through :)

**Review by emilyaherbert — APPROVED** [review]

**Pull request merged**
