### PR TITLE
Fix annotation span bug #1365

### PR DESCRIPTION
**Pull request by canndrew**

### CODE REVIEW

**Comment by otrho** [comment]
This change prevents the panic, but it seems to swallow the error message.

Before this patch:
```
: ../forc build
  Compiled library "core".
  Compiled library "std".
  Compiled library "foolib".
thread 'main' panicked at 'SourceAnnotation range `(0, 1)` is bigger than source length `0`', /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/annotate-snippets-0.9.1/src/display_list/from_snippet.rs:286:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
: ../forc build
  Compiled library "core".
  Compiled library "std".
  Compiled library "foolib".
error
 |
 |
____

  Aborting due to 1 error.
Error: Failed to compile foocaller
```
Prior to the span changes it would produce a slightly malformed but not entirely empty error:
```
: ../forc build
  Compiled library "core".
  Compiled library "std".
  Compiled library "foolib".
error
--> :0:1
 |
0 | Source span not available.
 | ^ Internal compiler error: Verification failed: Attempt to insert value of incorrect type into a struct.
```

**Comment by otrho** [comment]
Admittedly it's hard to reproduce.  You need the compiler to produce an error with a `Span::dummy()` deliberately.

**Comment by adlerjohn** [comment]
Is there no way to reproduce this in practice?

**Comment by sezna** [comment]
cc @canndrew and @otrho regarding @adlerjohn 's question?

**Comment by Braqzen** [comment]
@adlerjohn @sezna see [how to reproduce](https://github.com/FuelLabs/sway/issues/1365#issuecomment-1111468435)

**Comment by otrho** [comment]
Generally the only place we use dummy empty spans are for errors with no obvious code correlation, which are progressively becoming rarer as the code matures.  We should only see this sort of thing with ICEs, which are hard to deliberately repro.

**Comment by otrho** [comment]
Before:
```
warning                                                                                                                                                                                                     
 --> braqzen_repro/src/main.sw:8:5                                                                                                                                                                          
  |                                                                                                                                                                                                         
6 |                                                                                                                                                                                                         
7 | storage {                                                                                                                                                                                               
8 |     approved: bool                                                                                                                                                                                      
  |     -------- This storage declaration is never accessed and can be removed.                                                                                                                             
9 | }                                                                                                                                                                                                       
  |                                                                                                                                                                                                         
____                                                                                                                                                                                                        
                                                                                                                                                                                                            
thread 'main' panicked at 'SourceAnnotation range `(0, 1)` is bigger than source length `0`', /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/annotate-snippets-0.9.1/src/display_list/from_snipp
et.rs:286:9                                                                                           
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
warning
 --> braqzen_repro/src/main.sw:8:5
  |
6 | 
7 | storage {
8 |     approved: bool
  |     -------- This storage declaration is never accessed and can be removed.
9 | }
  |
____

error: Internal compiler error: Verification failed: State access operation must be to a u64 pointer.
Please file an issue on the repository and include the code that triggered this error.
____

  Aborting due to 1 error.
Error: Failed to compile braqzen_repro
```

**Review by sezna — APPROVED** [review]
It would be nice to fix the ICE but this is an incremental improvement, so LGTM…

**Comment by adlerjohn** [comment]
Can we get an issue filed with the repro?

**Comment by sezna** [comment]
I think it could be included under #1432? cc @otrho how do we remove all potential ICE cases from verification?

**Comment by otrho** [comment]
Yeah #1432 is a reaction to this issue.  They are the epitome of ICEs though -- they indicate that the compiler has created some invalid IR -- so that doesn't need to change necessarily.  So ideally we should never see them, but if a general user was to get one at the moment it isn't obvious what they should even submit in a bug report.

**Pull request merged**
