### PR TITLE
Suppress dead code warnings for blocks with errors

### PR DESCRIPTION
**Pull request by sdankel**
## Description

Closes https://github.com/FuelLabs/sway/issues/4000 and https://github.com/FuelLabs/sway/issues/3803

Before:

image

After: 

image

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
I guess in the original implementation you have the warning and the error display in the terminal when compiling which is probably what you want still. 

It just seems that we want to prefer displaying errors over code_block warnings in the server. Perhaps we could instead check in the server if the error has a span within the span of any warnings, and if so, discard converting the warning into a diagnostic?

**Comment by sdankel** [comment]
> I guess in the original implementation you have the warning and the error display in the terminal when compiling which is probably what you want still.
> 
> It just seems that we want to prefer displaying errors over code_block warnings in the server. Perhaps we could instead check in the server if the error has a span within the span of any warnings, and if so, discard converting the warning into a diagnostic?

The issue is that in many cases when there is an error in sway, it will return a dead code warning that would otherwise not be returned. It seems like when the code has a compiler error, the compiler thinks the code is unreachable because it's not a valid declaration. Even if something else references it, the compiler does not store that reference in the graph it uses to check for dead code.

Here's an example of this. When it has the compiler error, in this case `Storage attribute access mismatch. The function "test_function" in ABI "MyContract" requires the storage attribute(s) #[storage(read)].`, it also has a dead code error over the entire block.

When the storage attribute mismatch error is fixed, the compiler no longer says it's dead code.

Feb-06-2023 16-46-59

This is why I think we should just suppress dead code warnings when there is an error in the code block. Ideally the compiler would be sophisticated enough to tell that erroneous code is still being referenced, but that seems like a more fundamental change/fix.

I think the UX of not seeing any potentially legitimate dead code warnings until the errors are fixed (false negatives) is better than the current UX where we often report warnings that we shouldn't (false positives).

This seems to be closer to Rust's approach, for example, if I provide an extra argument in a trait impl, it only highlights the arguments, it doesn't mark the whole impl as dead code, like sway does today.

rust:
image

sway: 
image

**Comment by sdankel** [comment]
There are other types warnings too that don't get reported by the sway compiler until after the errors have been resolved. For example, if I fix the error in the code in the PR description, I see warnings about casting that weren't there before:

image

So this pattern of not reporting all warnings until the errors are fixed has a precedent in sway.

**Comment by JoshuaBatty** [comment]
> I think the UX of not seeing any potentially legitimate dead code warnings until the errors are fixed (false negatives) is better than the current UX where we often report warnings that we shouldn't (false positives).

Thanks for providing more clarification into what is happening in DCA. I agree that this change does improve the existing UX.

**Review by JoshuaBatty — APPROVED** [review]
Happy to approve this, interested to hear what @mohammadfawaz thinks about the DCA issues that have been noticed though.

**Pull request merged**
