### PR TITLE
Add `size_of` functionality.

### PR DESCRIPTION
**Pull request by emilyaherbert**
Closes one of the items here: https://github.com/FuelLabs/swayswap-demo/issues/1

### CODE REVIEW

**Comment by adlerjohn** [comment]
:mask_parrot:

**Comment by sezna** [comment]
Doesn't `size_of` typically take a _type_, like in C, C++, Rust, et al?

i.e. `size_of(u32) == 4`, `size_of(u64) == 8`? We should probably be consistent.

**Comment by sezna** [comment]
e.g. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a7de68b99dbb11c2afefebf31909f8c0

**Comment by otrho** [comment]
Not 100% relevant, but `sizeof` in C and C++ can take an expression, it just finds the size of the static type.  But yeah, it looks like Rust only does types.

**Review by otrho — COMMENTED** [review]
Looks good except is there a reason why it has to go all the way to codegen, and not be computed during semantic analysis?  Once everything is type checked then the expression within the `SizeOf` should have a known size and we can replace it with a `u64` const.

Sending it to ASM will also make it ripe for optimisation, especially via IR, but I made an issue #407 a while ago showing that we'll need compile time const evaluation eventually, and I imagine const expressions like `size_of` would fall into this area.

**Comment by emilyaherbert** [comment]
Per the discussion on Slack, I will rename the current implementation of `size_of(x)` to `size_of_val(x)` to mimic Rust's function of the same name. I will also implement `size_of<T>()` so that we can have both options 😄 

@otrho To answer your question, `SizeOf` needs to go all the way to codegen because it may be the case that in the body of the function you could have a call to a function with a side effect (or something to that end). Something like `size_of_val(function_that_has_a_side_effect_and_also_returns_a_value())`.

**Comment by otrho** [comment]
> you could have a call to a function with a side effect

OK, fair enough.  `size_of_val()` is pretty unique in that regard.  I've never seen that in other languages. :)

Maybe with regard to having a const compile time evaluated expression in the future we could do both -- know the type, and therefore know the size at compile time, but call the side effects too.

**Comment by emilyaherbert** [comment]
> Maybe with regard to having a const compile time evaluated expression in the future we could do both -- know the type, and therefore know the size at compile time, but call the side effects too.

Maybe I'm missing something, but is there any reason to add this implementation complexity? It seems sufficient to me to transform `size_of_val(x)` during codegen in a general way, as it is implemented currently.

**Comment by otrho** [comment]
I'm assuming that one day we might want to use `size_of` in a `const` declaration, or in an array type.  In these cases the `size_of` must be known at compile time else we can't type-check.  Maybe that assumption is wrong.

We don't need it now, but maybe one day.  The only times I've ever needed to use `size_of` in the past is for low level manipulation, like serialisation to/from a byte buffer or changing endianess of an integer, and in these cases knowing the size at compile time is way more efficient.

**Review by otrho — DISMISSED** [review]

**Comment by adlerjohn** [comment]
Merge conflict: \*blocks your path\*

**Comment by adlerjohn** [comment]
> Merge conflict: \*blocks your path again\*

**Review by otrho — DISMISSED** [review]

**Review by adlerjohn — DISMISSED** [review]

**Comment by otrho** [comment]
@sezna and I have had a little chat and maybe, not sure, but maybe it'd be better to implement `size_of_val` in terms of `size_of` after all.
```rust
fn size_of_val<T>(exp: T) -> u64 {
  size_of(T)
}
```
Rust seems to use intrinsics rather than the above though.

**Comment by sezna** [comment]
I do feel like the above is simpler...what do you think @emilyaherbert? Could save a few lines of code 😄

**Comment by adlerjohn** [comment]
A cleaner impl could always be left to a `good first issue` issue?

**Comment by emilyaherbert** [comment]
> @sezna and I have had a little chat and maybe, not sure, but maybe it'd be better to implement `size_of_val` in terms of `size_of` after all.
> 
> ```rust
> fn size_of_val<T>(exp: T) -> u64 {
>   size_of(T)
> }
> ```
> 
> Rust seems to use intrinsics rather than the above though.

I'm going to lean against this suggestion a little bit.

1. This would mean that `size_of` would be available intrinsically and `size_of_val` would be available via a library. I don't really like how that feels from a user experience perspective. I feel like they should either both be intrinsic or both be available via a library.
2. The proposed function wouldn't compile anyway due to #827

**Comment by sezna** [comment]
> The proposed function wouldn't compile anyway due to https://github.com/FuelLabs/sway/issues/827

I left a comment there -- I'm not sure that's accurate. If it doesn't compile, that would be a bug anyway. 

Rust's `size_of_val` says the following about itself:
> This is usually the same as size_of::<T>(). However, when T has no statically-known size, e.g., a slice [[T]](https://doc.rust-lang.org/stable/std/primitive.slice.html) or a [trait object](https://doc.rust-lang.org/stable/book/ch17-02-trait-objects.html), then size_of_val can be used to get the dynamically-known size.

As we don't have these things (slices, trait objects, statically-sized types whose sizes don't exist until runtime), do you see an additional utility for `size_of_val`? Just keeping in mind the goal of being able to use `LOGD` and serialization on a type, design-wise.

**Comment by emilyaherbert** [comment]
I wrote a lot on #827 related to this.

> As we don't have these things (slices, trait objects, statically-sized types whose sizes don't exist until runtime), do you see an additional utility for size_of_val? Just keeping in mind the goal of being able to use LOGD and serialization on a type, design-wise.

I don't see any utility for `size_of_val` other than ease of use and the fact that it works inside of a generic function when `size_of` does not (see #827).

For example, this Sway compiles:

```rust
script;

use std::chain::assert;

fn find_the_size<T>(elem: T) -> u64 {
  size_of_val(elem)
}

fn main() -> u64 {
    assert(find_the_size(7u64) == 8);
    1
}
```

while this does not:

```rust
script;

use std::chain::assert;

fn find_the_size<T>(elem: T) -> u64 {
  size_of::<T>()
}

fn main() -> u64 {
    assert(find_the_size(7u64) == 8);
    1
}
```

**Comment by sezna** [comment]
Ok we have decided to take this in, and when #827 gets fixed we can fix `size_of`

**Review by sezna — APPROVED** [review]

**Pull request merged**
