### PR TITLE
Compiler error when using private methods of library.

### LINKED ISSUE #3327: Impl self methods should respect the `pub` keyword
Currently, the `pub` keyword is ignored for impl self methods. Example

Library code:
```rust
library lib;

pub struct MyStruct {
    x: u64,
}

impl MyStruct {
    fn foo(self) {}

    fn bar() {}
}
```
Script code:
```rust
script;

dep lib;

use lib::*;

fn main() {
    MyStruct { x: 42 }.foo();
    MyStruct::bar();
}
```
This compiles fine. Instead, it should complain that `foo` and `bar` are not `pub`.

### PR DESCRIPTION
**Pull request by esdrubal**
The compiler now returns an error when using private methods of impl defined in another file.

Closes #3327

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Thanks for doing this! I think we're violating this requirement in the standard library. For example, https://github.com/FuelLabs/sway/blob/e7f4bd3b61b1085913da1b918cc7256dcdf94ad3/sway-lib-std/src/result.sw#L28 should be marked `pub`. Do you mind going through the `core` and `std` and making sure all methods are updated? Note that impl trait methods should not be updated, only impl self.

**Comment by esdrubal** [comment]
> Do you mind going through the `core` and `std` and making sure all methods are updated?

Ok, I will do that.

**Comment by esdrubal** [comment]
`test/src/sdk-harness/test_projects/evm_ec_recover` is fetching lib-std from github, any reason for it to not do `implicit-std=false` and using local std dependency?

**Comment by mohammadfawaz** [comment]
> `test/src/sdk-harness/test_projects/evm_ec_recover` is fetching lib-std from github, any reason for it to not do `implicit-std=false` and using local std dependency?

Nops, that's probably an oversight. Feel free to change :)

**Comment by mohammadfawaz** [comment]
Merge conflicts :(

**Review by mohammadfawaz — APPROVED** [review]

**Pull request merged**
