### PR TITLE
Explain VSCode formatter

### PR DESCRIPTION
**Pull request by paulrberg**
The `editor.defaultFormatter` global VSCode setting is often set to a cross-language formatter like Prettier.

To remind the reader of this, I have added a note in "The Fuel Toolchain" about how to override this setting for Sway files.

Note: this PR depends upon #3388 being merged first.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Seems that this requires https://github.com/FuelLabs/sway/pull/3388 to go in first. You may alternatively remove the changes to `overview.md` here so that the two PRs can be approved in parallel.

**Comment by paulrberg** [comment]
Happy to way for #3388 to be merged first!

**Comment by mohammadfawaz** [comment]
> Happy to way for #3388 to be merged first!

Great! There are now some conflicts that need to be resolved because we can approve.

**Comment by paulrberg** [comment]
Fixed!

**Comment by kayagokalp** [comment]
@paulrberg thanks 👍 seems like we have couple of md linting errors here, would you mind tackling them first? If you don't have a md linter installed you can look the errors from [CI](https://github.com/FuelLabs/sway/actions/runs/3522563575/jobs/5905687664).

**Comment by paulrberg** [comment]
Shoot, I have accidentally committed the git conflicts files. Should be fine now.

**Review by kayagokalp — APPROVED** [review]
lgtm, but i am not using vscode thus not exposed to vscode plugin :) Will be requesting another review from @JoshuaBatty @sdankel.

**Review by JoshuaBatty — APPROVED** [review]
Excellent, thanks for the PR!

**Pull request merged**
