### PR TITLE
Remove impure keyword

### PR DESCRIPTION
**Pull request by ra0x3**
### Description
- This PR removes support for the `impure` keyword

# Testing Steps
- TBD

### CODE REVIEW

**Comment by ra0x3** [comment]
@adlerjohn I was combing through issues and found this one. Let me know if I'm very off with this.

**Comment by adlerjohn** [comment]
looping in @otrho

**Comment by otrho** [comment]
Ahh, bugger, I've already done this in #1518.  I should've searched for and assigned myself that issue, sorry.

**Comment by adlerjohn** [comment]
Closing as dup, sorry 😞

**Pull request closed without merging**
