### PR TITLE
Refactor usage of namespaces to improve compiler performance

### LINKED ISSUE #678: `forc build` crashes when compiling and exits with `Killed`
Was trying to compile my most recent [BentoBox Build](https://github.com/ControlCplusControlV/Sushi-Sway) but upon attempting to compile with forc build the compile process exits with Killed instead of a byte size or an error when compiling

```
controlC@my-pc:~Sushi-Sway$ forc build
  Compiled library "core".
  Compiled library "core".
warning
 --> FuelLabs-sway-lib-std-15bed83/src/result.sw:0:5
  |
...
3 |     Ok: T,
  |     -- Enum variant Ok is never constructed.
  |
warning
 --> FuelLabs-sway-lib-std-15bed83/src/result.sw:0:5
  |
...
4 |     Err: E,
  |     --- Enum variant Err is never constructed.
  |
  Compiled library "lib-std" with 2 warnings.
Killed
```
I am not cancelling the process with control c or any other keystrokes, so I am not sure why it is resulting in a Killed message rather than any other error message

### PR DESCRIPTION
**Pull request by sezna**
The compiler has been getting more and more sluggish due to some poorly scaling decisions I made back in the beginning of this project. Generally, this PR refactors the usage of namespaces as a metaphor for scopes. Previously, cloning namespaces happened to denote a new "scope". This is common when writing a compiler in a functional language with a garbage collector for a small language, and is what I learned in compilers class. Well, these namespaces are usually not modified and are cloned _a lot_, which means exponential memory growth and performance loss.

Overall I tried not to touch codegen since that will be improved with IR anyway -- these changes are almost entirely in the semantic analysis module.

### Overview
This PR:
1. Modifies constant declarations to just be immutable variable declarations, although they remain more or less functionally the same
2. Introduces an arena which contains all modules and hands out references to those modules. Accessing a module can be done via `read_module` or `write_module`, which take a function that modifies or reads a module and the id of that module and handles it accordingly. The general idea is that while cloning namespaces is now much quicker, if you truly need to make a new scope, use `create_new_scope` instead of cloning the namespace. 

### Further Work/Drawbacks
1. Using an `RwLock` can leave us vulnerable to deadlocks. I would like to refactor this into a concurrent slab or similar, like how @canndrew did to the last `RwLock`-based refactoring I did. I need to learn a bit more about how to design that, though.
2. Trait namespaces are still pretty hard to deal with.

Closes #678

### CODE REVIEW

**Review by emilyaherbert — APPROVED** [review]

**Comment by emilyaherbert** [comment]
LGTM! Great work @sezna!

**Comment by emilyaherbert** [comment]
Will you make issues for the "further work" items?

**Review by adlerjohn — APPROVED** [review]
Green checkmark means go

**Comment by sezna** [comment]
> Will you make issues for the "further work" items?

Yep I can do that now

**Pull request merged**
