### PR TITLE
Add increment functionality to `b256`

### LINKED ISSUE #4781: Add functionality to increment a `b256`
# Description

The Sway language does not currently support any mathematical operations on a `b256`. Fuel core v0.19 support will add the `WQOP` op code for add, sub, shifts, etc but until then an increment by `u64` function may be implemented.

https://github.com/FuelLabs/fuel-specs/blob/master/src/fuel-vm/instruction-set.md#wqop-misc-256-bit-integer-operations

# Motivation

This functionality is required to optimize storage read/write operations.

### PR DESCRIPTION
**Pull request by bitzoic**
## Description

There are currently no mathematical operations allowed on a b256 in Sway. This should come with support of fuel-core v0.19.0 but for now we are able to add an increment function now.

This is *critical* functionality to storage optimizations that are in progress.

- Adds increment functionality to b256
- Moves and modifies overflowing add for u64 to the maths library
- Modifies the u128 and u256 libraries with new overflowing add 

Closes #4781 

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by Braqzen — APPROVED** [review]
utACK, mainly approving based on tests

**Comment by SwayStar123** [comment]
I dont see any tests for testing that the b256 doesnt overflow

**Comment by bitzoic** [comment]
> I dont see any tests for testing that the b256 doesnt overflow

As far as I'm aware there is no `#[should_panic]` for inline tests yet

**Comment by anton-trunov** [comment]
@bitzoic You can add it as an end-to-end test, perhaps. Those can expect panics

**Review by IGI-111 — CHANGES_REQUESTED** [review]
As we discussed, I think that `b256` shouldn't have arithmetic operations, and that we should introduce a `u256` primitive type instead to support those.

**Pull request closed without merging**
