### PR TITLE
Remove `sway_types::{JsonABI, Function, Property}` in favour of `fuels_types`

### PR DESCRIPTION
**Pull request by mitchmindtree**
See https://github.com/FuelLabs/fuels-rs/pull/219 for context.

## Blockers

- [x] Await `fuels-types` to get published.

## TODO

- [x] Update `Cargo.toml`s to point to published version.
- [x] Update `Cargo.lock`.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Is this blocked by something or is it ready to be reviewed? :)

**Review by eureka-cpu — COMMENTED** [review]
lgtm, deferring to @mohammadfawaz & @JoshuaBatty

**Comment by JoshuaBatty** [comment]
Also LGTM, but will wait for @mitchmindtree to fix the conflicts first before giving approval.

**Comment by mitchmindtree** [comment]
OK, conflicts resolved!

**Review by vnepveu — APPROVED** [review]
LGTM!

**Pull request merged**
