### PR TITLE
Migrate std-lib tests

### PR DESCRIPTION
**Pull request by nfurfaro**
Testing out Plan A: https://github.com/FuelLabs/sway/issues/1058#issuecomment-1104120265

If we like this direction,  a follow-up issue could be to migrate all stdlib tests (there aren't many) out of the e2e test harness.

closes: #1058

### CODE REVIEW

**Review by JoshuaBatty — CHANGES_REQUESTED** [review]
There seem to be a few .DS_Store files accidentally committed, can these be removed...

**Comment by nfurfaro** [comment]
@JoshuaBatty for sure! I thought I deleted all of those, will do asap.

**Review by sezna — DISMISSED** [review]
LGTM, ds store should probably be in the gitignore though...

**Comment by nfurfaro** [comment]
>ds store should probably be in the gitignore though...
I've added it to my local .gitignore_global so I don't make that mistake again. Maybe a separate PR can add it to the sway .gitignore

**Review by JoshuaBatty — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
