### PR TITLE
Added tests for the `sqrt()` method in `math.sw`

### LINKED ISSUE #5330: `math.sw` is missing tests
It appears that most of the functionality in that module is untested, at least in Sway.
If it's tested in our Rust suite then it's not easily findable.

We should test the module.

### PR DESCRIPTION
**Pull request by brandonsurh**
## Description
Closes #5330

Previously, there were no tests for the `sqrt()` method in `math.sw`. This adds square root tests in the Rust test suite.
Other tests are found here:
- [`pow()`](https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/src/main.sw)
- [`log()` and `log2()`](https://github.com/FuelLabs/sway/blob/master/test/src/e2e_vm_tests/test_programs/should_pass/stdlib/logarithmic_test/src/main.sw)

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by xunilrj** [comment]
Nice, but these can be unit tests inside the stdlib, right? `sway-lib-std/src/math.sw` has an example already.

**Comment by brandonsurh** [comment]
> Nice, but these can be unit tests inside the stdlib, right? `sway-lib-std/src/math.sw` has an example already.

You are correct. I would actually prefer the tests for `math.sw` to be right in there, but the pre-existing ones for `pow()`, `log()`, and `log2()` were made elsewhere. The reason I placed them in the Rust suite was to keep things uniform, but if desired I can move all of them into `math.sw`.

**Comment by xunilrj** [comment]
>  but if desired I can move all of them into math.sw.

If possible I think makes more sense. Thanks! :D

**Review by xunilrj — APPROVED** [review]

**Comment by brandonsurh** [comment]
> If possible I think makes more sense. Thanks! :D

Moved the tests for `pow()`, `log()`, and `log2()` into `math.sw`. Everything should be good on that front! However, may need to take a look at the failing checks.

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
