### PR TITLE
Fixed `self` in trait methods

### LINKED ISSUE #3805: `forc doc`: Problem formatting `self` in function parameters of trait methods
This has to do with #3657 

I hastily made a formatter for trait methods, and in doing so inadvertently birthed this issue. I plan to tackle this while handling the aforementioned issue, but I'm opening this for consistency.

### PR DESCRIPTION
**Pull request by gr00vytvniks**
Closes #3805

### CODE REVIEW

**Review by kayagokalp — COMMENTED** [review]
👌 Hmm this makes me wonder if we can have some tests for `forc-doc` for catching this sort of regressions. I am not sure how to test the PR, so would be great to have @eureka-cpu's review/input :)

**Comment by gr00vytvniks** [comment]
> 👌 Hmm this makes me wonder if we can have some tests for `forc-doc` for catching this sort of regressions. I am not sure how to test the PR, so would be great to have @eureka-cpu's review/input :)

Here's how I tested:
```sh
cd ~/sway/forc-plugins/forc-doc
cargo install --path .
cd ~/sway/sway-lib-std
forc doc --open
```
just do this process on master, click on any method that includes self and then do the same on this branch to compare

**Comment by kayagokalp** [comment]
Ahh so this is a fix for all methods, got it 👍

**Review by eureka-cpu — APPROVED** [review]
Just tested, looks like that was all that was needed to fix it lol

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
