### PR TITLE
refactor: `forc-doc`- move headers above descriptions and add extra vertical spacing between items

### LINKED ISSUE #4432: Improve readability of forc doc
Right now the std-lib docs generated with forc doc are difficult to read due to the styling format where sub-headings are on the left and descriptions are on the right.

std-lib-docs

Making the headings go above the descriptions with vertical spacing in between each section would improve the readability of the docs significantly.

### PR DESCRIPTION
**Pull request by sarahschwartz**
close #4432

forc-doc-updates

### CODE REVIEW

**Comment by eureka-cpu** [comment]
Hey @sarahschwartz would you mind including a screen cap of the changes?

**Comment by eureka-cpu** [comment]
Ah I see what you mean now! I'm not sure if we want the previews under since it will make the page much longer vertically but I'll defer to  @mitchmindtree & @JoshuaBatty

**Comment by mitchmindtree** [comment]
I could go either way on this one, though my inclination is to stick to the table-style approach following suit with docs.rs ([e.g.](https://docs.rs/rand/latest/rand/)), mostly because these pages can become very dense depending on the number of items in the module, and the idea is more to show an overview/list of the items that exist within the module where the user can click in to learn more. 

I guess the problem with the table style approach is that sometimes you have to look close to see which preview is associated with each line. Perhaps we should use some kind of visual cue like a colour offset for every second row to make it a bit clearer?

Happy to go with what you recommend @sarahschwartz as you probably get the most feedback about the forc-doc UX!

**Comment by eureka-cpu** [comment]
> I could go either way on this one, though my inclination is to stick to the table-style approach following suit with docs.rs ([e.g.](https://docs.rs/rand/latest/rand/)), mostly because these pages can become very dense depending on the number of items in the module, and the idea is more to show an overview/list of the items that exist within the module where the user can click in to learn more. 
> 
> I guess the problem with the table style approach is that sometimes you have to look close to see which preview is associated with each line. Perhaps we should use some kind of visual cue like a colour offset for every second row to make it a bit clearer?
> 
> Happy to go with what you recommend @sarahschwartz as you probably get the most feedback about the forc-doc UX!

I like the idea about offsetting the color of each second line but keeping the old layout

**Comment by sarahschwartz** [comment]
Generally tables are used to display charts of data or statistics like a spreadsheet with column and row headers. I don't think it makes sense to use a table format for this type of content, but I do see the possible need to split some of the content up into different pages if they are too long. Pushing the content into a smaller space may allow it to fit in a smaller space, but this becomes less accessible / readable as well.

I also understand the desire to mirror Rust, but I don't believe this type of UI design jn particular is something that was well done or something developers really love about Rust.

**Comment by kayagokalp** [comment]
@sarahschwartz I changed the description of the PR so that it is a little more descriptive in `git log` once it is merged. Feel free to revert it back if you feel like it.

**Comment by mitchmindtree** [comment]
> I don't think it makes sense to use a table format for this type of content, but I do see the possible need to split some of the content up into different pages if they are too long.

Ohhh there might be some confusion w.r.t. the intentions for these module pages!

Originally, these were actually just *lists* of items to act as a point of easy navigation from the module level to the items it contains. The one-liner preview of the docs was added on the right just to show a little more context on what you can navigate into. Most of those item-level docs are very small right now and just *happen* to almost fit into the one line, however eventually (once sway-lib-std is documented _properly_) they be should be much more extensive with multiple tested examples, information about performance trade-offs, context on when and where to use them, etc.

Does this help to clarify the original intent a little? Knowing this, do you still think we might be better with the line breaks and larger previews? I think I'm still open to it, though I think we'd want to have some nice heuristic for trimming previews to a couple lines, or just the first sentence or something so that we don't make it too hard to quickly scan through all the items.

**Comment by eureka-cpu** [comment]
Hm, I still think it may be better keep the original formatting since it aligns with how `cargo doc` produces documentation. If it's a matter of being able to find what you're looking for there is an issue open for organising links alphabetically? In general, `forc doc` is immature in comparison to the `cargo` documenter, and with the growth it will have in the coming month I believe it will make the user interface more friendly and keeping it familiar to rust users is definitely the priority.

In general, I think the right approach is to follow in `cargo doc`'s footsteps. I appreciate the want to make `forc doc` better though, and there are a good number of issues I think would be good first issues to tackle such as the aforementioned alphabetization one.

**Comment by sarahschwartz** [comment]
I'm not confused about this, but I appreciate you explaining your logic. 

For the Dev Rel team, we frequently receive requests to better document the standard library. 
We believe that the official Fuel documentation should eventually (soon) have a consistent Fuel branding and design system, which won't exactly mirror Rust's. Unless you think we should create an entirely separate documentation resource for the standard library, this documentation will eventually have to align with that design system.

This PR was meant to be a sort of quick fix to improve the accessibility of these docs for the time being. I'm definitely open to different designs and solutions, but I strongly believe a table format is not the correct format here.

**Comment by eureka-cpu** [comment]
> Unless you think we should create an entirely separate documentation resource for the standard library, this documentation will eventually have to align with that design system.


If that's the case it may make more sense to do that

> This PR was meant to be a sort of quick fix to improve the accessibility of these docs for the time being. I'm definitely open to different designs and solutions, but I strongly believe a table format is not the correct format here.

I understand the Dev rel team has a goal in mind for how they would like the documentation for the standard library to look, but I don't think it makes sense to change the look of the documentation produced by `forc doc` just to serve this purpose.

I would recommend working out the design for the standard library documentation in an issue and if it's decided that the structure of `forc doc` should stray from `cargo`'s we can go from there.

**Review by mitchmindtree — APPROVED** [review]
> For the Dev Rel team, we frequently receive requests to better document the standard library.
We believe that the official Fuel documentation should eventually (soon) have a consistent Fuel branding and design system, which won't exactly mirror Rust's. Unless you think we should create an entirely separate documentation resource for the standard library, this documentation will eventually have to align with that design system.

Thanks for sharing some more context! I think no-one is in a better position to make these kinds of design/style/feedback judgements than you guys, so if you feel it's best I'm happy to see this land - especially if it's a part of a wider effort for consistency across all Fuel docs.

I'm excited to see devrel dig into the std doc content, it's definitely sorely lacking atm :smiling_face_with_tear: fwiw, I left some thoughts [here](https://github.com/FuelLabs/sway/issues/1066#issuecomment-1442685135) recently.

> I understand the Dev rel team has a goal in mind for how they would like the documentation for the standard library to look, but I don't think it makes sense to change the look of the documentation produced by forc doc just to serve this purpose.

I think if the std docs can benefit, then likely the wider `forc doc`-generated docs might also benefit anyways. Eventually, I'm imagining we'll host *all* ecosystem package docs under some `docs.rs` style domain like `docs.fuel.network/std`, `docs.fuel.network/core`, `docs.fuel.network/nft`, etc (or something along these lines) and we'll likely want some consistency.

---

Just tested locally, LGTM

**Review by JoshuaBatty — APPROVED** [review]

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
