### PR TITLE
Annotate ItemStorage fields

### PR DESCRIPTION
**Pull request by AlicanC**
This PR adds support for attaching Attributes to storage fields, similar to #2528 which adds this support for enum and struct fields.

### CODE REVIEW

**Comment by sezna** [comment]
I notice both this PR and #2528 say `TODO -- handle annotations` -- do we just parse them and discard them right now? If so, could you file an issue to handle adding them to the AST?

**Review by mohammadfawaz — APPROVED** [review]
Seems reasonable. Thanks!

**Comment by AlicanC** [comment]
> I notice both this PR and #2528 say `TODO -- handle annotations` -- do we just parse them and discard them right now? If so, could you file an issue to handle adding them to the AST?

Yup, that's the case. Created the issue: https://github.com/FuelLabs/sway/issues/2589

**Review by sezna — APPROVED** [review]
Thanks!

**Pull request merged**
