### PR TITLE
Adds support for where clauses in impl self methods.

### LINKED ISSUE #3333: Can't use generic type parameters from `impl<>` in impl self methods
Code:
```rust
script;

use core::ops::*;


struct Vec<T> {
    x: T
}

impl<T> Vec<T> {
    fn contains(self, other: T) -> bool where T: Eq { 
        true
    }
}

fn main() { }
```
I expect the above to work so that I can compare `self` with `other` in the body of `contains`. Instead, I get:
```console
10 | impl<T> Vec<T> {
11 |     fn contains(self, other: T) -> bool where T: Eq {
   |                                               ^ cannot find type "T" in this scope
12 |         true
13 |     }
   |
```

### PR DESCRIPTION
**Pull request by esdrubal**
When where clauses were used in impl self methods with a generic parameter from
 impl<T> an error was thrown saying `cannot find type "T" in this scope`

Parent type parameters that are used in method where clauses are now added to `FunctionDeclaration.type_parameters`.
This is needed for `TypeParameter::gather_decl_mapping_from_trait_constraints` to work properly as we need to have a type parameter with constraints. The generated decl_mapping is used by `type_check_method_application` to replace decls from trait constraints.

Closes #3333

### CODE REVIEW

**Review by emilyaherbert — CHANGES_REQUESTED** [review]
For bookkeeping---requesting changes on this PR for this reason:

https://github.com/FuelLabs/sway/pull/3621#issuecomment-1402757205

**Comment by esdrubal** [comment]
Reopen the PR up for review.

The PR still uses the `TypeParameter` with `is_from_parent`. This looks like a cleaner approach than moving `TraitConstraint` out of `TypeParameter`. Because a trait constraint is always relative to a type parameter.

**Comment by sdankel** [comment]
Looks like there are some merge conflicts. It would be nice to have this fixed!

**Comment by esdrubal** [comment]
The merge conflicts are now resolved.

**Review by IGI-111 — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
