### PR TITLE
Bugfix: use the index param in std::tx::tx_witness_pointer

### LINKED ISSUE #4429: `std::tx::tx_witness_pointer` does not use `index`
See: https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/tx.sw#L114-L119. Not sure why `index` is not used but it probably should be according to the spec of `gtf`.

### PR DESCRIPTION
**Pull request by nfurfaro**
## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

Closes #4429

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Awesome. Is it possible to add a test for this? Or is this too complicated to do in the SDK test?

**Comment by mohammadfawaz** [comment]
> >Awesome. Is it possible to add a test for this?
> 
> 
> 
> I could add another test. The current test was passing `0` as the index, and while the index param was not being used, `0` was hardcoded. So this was already tested, and coincidentally the change to the stdlib didn't require any changes to the test.
> 
> https://github.com/FuelLabs/sway/blob/abddf732125d8391f37ee5459c4ddad2c0abdb38/test/src/sdk-harness/test_projects/tx_fields/mod.rs#L309
> 
> 

Yeah I'm just thinking of the non-zero index case that should pass now (but would have failed before)!

**Comment by nfurfaro** [comment]
Got it. 
I'll work out how to sign the tx a second time with another wallet. 
Otherwise, there's only 1 witness and any index > 0 fails.

**Review by Braqzen — APPROVED** [review]
It would be good to do something about the magic number `11032` in the assert since idk what that is or why it changed.

**Pull request merged**
