### PR TITLE
Bump to v0.48.0

### PR DESCRIPTION
**Pull request by JoshuaBatty**
waiting on 
* #5274 
* #5273
* #5281

### CODE REVIEW

**Review by kayagokalp — DISMISSED** [review]

**Comment by IGI-111** [comment]
@ironcev Can you look at that failing test?

**Comment by JoshuaBatty** [comment]
I think it was locked to v0.47 of the std lib. I've just updated it to

```
[[package]]
name = 'trait_cannot_find_in_scope_issue'
source = 'member'
```

**Comment by kayagokalp** [comment]
> I think it was locked to v0.47 of the std lib. I've just updated it to
> 
> ```
> [[package]]
> name = 'trait_cannot_find_in_scope_issue'
> source = 'member'
> ```

I feel like this might not work because std of 0.48 is not released yet but forc will try to get that one. We should always point to std by path in test suite to prevenet issues popping out while releasing.

```
[project]
name = "trait_cannot_find_in_scope_issue"
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"


[dependencies]
std = { path = "../../../../../sway-lib-std" }
```

Note: I am writing this without having access to the file structure at the moment so amount of `../`s might be invalid in the given example above

**Comment by kayagokalp** [comment]
d6c8c155e73b611372a61864055e959e0bf7bd06 was missing the lock file for the test with std pointing to local. That would also cause test suite to fail as forc will throw warnings. I added the lock file back with std pointed to local version. (simply executed forc build after d6c8c155e73b611372a61864055e959e0bf7bd06) in 2875be862ed39bbdcb88a83efc74809be0575bee.

**Comment by JoshuaBatty** [comment]
Thanks, @kayagokalp :)

**Review by IGI-111 — APPROVED** [review]

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
