### PR TITLE
Updated the sway.js file by adding mod and type in keyword

### LINKED ISSUE #4424: Add keywords `mod` & `type` to sway.js
New keywords exist but have not been added to the [sway.js](https://github.com/FuelLabs/sway/blob/master/scripts/highlightjs/sway.js) file.

### PR DESCRIPTION
**Pull request by Yasir761**
## Description
fixes #4424 
closes #4424 

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
thanks for the PR. Would you mind removing the `dep` keyword as well now that we have mod?

**Comment by mohammadfawaz** [comment]
Thanks @Yasir761. Do you mind also running `./build.sh` in https://github.com/FuelLabs/sway/tree/master/scripts/highlightjs?

**Comment by Yasir761** [comment]
> thanks for the PR. Would you mind removing the `dep` keyword as well now that we have `mod`?

I made change as you suggested, Please take a review.
Thank You

**Comment by Yasir761** [comment]
> Thanks @Yasir761. Do you mind also running `./build.sh` in https://github.com/FuelLabs/sway/tree/master/scripts/highlightjs?

I ran command 'build.sh', Please have a look.
Thank You

**Review by mohammadfawaz — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Pull request merged**
