### PR TITLE
Update readme for stdlib tests

### PR DESCRIPTION
**Pull request by nfurfaro**
Updated the location of the build script and linked to the docs for `forc test`

### CODE REVIEW

**Review by Braqzen — CHANGES_REQUESTED** [review]
I would add in the `$` at the start of each command namely lines 8, 9, 15, 16 and 23 to make a distinction between a command and comment. It might be considered pedantic but I think consistency and convention are good to follow

**Comment by adlerjohn** [comment]
@Braqzen the book uses `sh` for commands with no output and `console` with `$` for commands + their output. I'm not sure where comments come into play?

**Comment by nfurfaro** [comment]
@Braqzen In this case, using markdownlint to format the doc stripped out all the `$` symbols.

https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Review by Braqzen — APPROVED** [review]

**Comment by otrho** [comment]
Another thing to consider is if we are happy with users copy-n-pasting the examples into their terminal.  The `$` prevents this from being easy, which could be good or bad.

**Pull request merged**
