### PR TITLE
Bump to v0.17.0

### PR DESCRIPTION
**Pull request by mohammadfawaz**
* Bump to v0.17.0
* Run `cargo update`

Waiting on:
- [x] https://github.com/FuelLabs/sway/pull/2189
- [x] https://github.com/FuelLabs/sway/pull/2112
- [ ] https://github.com/FuelLabs/sway/pull/2127
- [x] https://github.com/FuelLabs/sway/pull/2096
- [x] https://github.com/FuelLabs/sway/pull/2193

### CODE REVIEW

**Comment by mitchmindtree** [comment]
I wonder if we should set a convention of trying to land a `cargo update` along with each of these releases, to make sure we're shipping with the latest security patches etc? If CI fails after `cargo update`, we can always go without.

**Comment by mohammadfawaz** [comment]
> I wonder if we should set a convention of trying to land a `cargo update` along with each of these releases, to make sure we're shipping with the latest security patches etc? If CI fails after `cargo update`, we can always go without.

I think that's a very good idea. Should this be done with every release (including non-breaking ones) or just minor releases? Cc @adlerjohn @sezna @JoshuaBatty.

**Comment by sezna** [comment]
My inclination is to say every minor release, to avoid the risk of transitive dependencies perhaps not upholding semver

**Review by sezna — APPROVED** [review]

**Comment by mohammadfawaz** [comment]
> My inclination is to say every minor release, to avoid the risk of transitive dependencies perhaps not upholding semver

Makes sense. I had a similar feeling which is why I asked :)

**Review by mitchmindtree — APPROVED** [review]
> My inclination is to say every minor release, to avoid the risk of transitive dependencies perhaps not upholding semver

Yeah SGTM

**Comment by JoshuaBatty** [comment]
> My inclination is to say every minor release, to avoid the risk of transitive dependencies perhaps not upholding semver

Also agree this is the correct approach.

**Pull request merged**
