### PR TITLE
Introduce `DeclRef` and remove excessive clones to `DeclId`

### PR DESCRIPTION
**Pull request by emilyaherbert**
## Description

This PR is a subset of #3744. It introduces `DeclRef`, which is a smart wrapper type around `DeclId` and contains additional information aside from the `DeclId`. This allows us to make `DeclId` a copy type and remove excessive clones of `DeclId` and `DeclRef`.

This PR is a subset of #3744, so while not explicitly necessary right now on `master`, there will be additional fields added to `DeclRef` in #3744.

In detail, this PR:
1. Changes `DeclId` to a copy type defined as:
    ```rust
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
    pub struct DeclId(usize);
    ```
2. Creates a new `DeclRef` type which is a handle to a use of a declaration: (there will be more fields added to this in #3744)
    ```rust
    /// A reference to the use of a declaration.
    #[derive(Debug, Clone)]
    struct DeclRef {
        /// The name of the declaration.
        name: Ident,
        /// The index into the [DeclEngine].
        id: DeclId,
        /// The [Span] of the entire declaration.
        decl_span: Span,
    }
    ```
3. Changes the definition of the `TyDeclaration::FunctionDeclaration` variant to contain additional fields: (there will be more fields added to this in #3744)
    ```rust
        FunctionDeclaration {
            name: Ident,
            decl_id: DeclId,
            decl_span: Span,
        },
    ```
4. Changes the definiton of the `TyExpressionVariant::FunctionApplication` variant to contain a `DeclRef` instead of just the previous `DeclId`. The `TyExpressionVariant::FunctionApplication` variant gets a `DeclRef` because `DeclRef` is a handle to a declaration _usage_, while the `TyDeclaration::FunctionDeclaration` variant does not get a `DeclRef` because it is simply an AST node for the function declaration. This distinction will be more clear/necessary in #3744.
5. Changes other necessary variants, aside from `TyDeclaration::FunctionDeclaration` and `TyExpressionVariant::FunctionApplication`.
5. Changes the `DeclEngine` API to take `&T where ...`, allowing us to remove more unnecessary instances of `.clone()`.

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by mohammadfawaz — DISMISSED** [review]
Makes sense.

**Comment by JoshuaBatty** [comment]
> 

I would ask that Spans and Idents be included wherever possible as they are the primary type that we rely on in the language server for doing anything.

**Comment by emilyaherbert** [comment]
> If I remember correctly that span is only used for a diagnostic which I've never even seen before. And can't we get the name from the declaration linked by the ID anyway?

Also the `DeclRef` type will get at least one additional field in #3744, so it's convenient to have the distinction. I'm trying to split up the refactoring bit of that PR before I submit "the real PR" ™️ with the core logic 😅

**Review by otrho — APPROVED** [review]
utACK.  Can see most of it is `DeclId` -> `DeclRef`, LGTM.

**Review by JoshuaBatty — APPROVED** [review]
Nice, looks good!

**Pull request merged**
