### PR TITLE
Implicitly add `std` dependency if unspecified

### LINKED ISSUE #330: Implicitly include `std` and `core` when undeclared in the `Forc.toml`
Currently, the standard library needs to be manually imported in the `Forc.toml` file. We should actually automatically import that.

### PR DESCRIPTION
**Pull request by mitchmindtree**
While loading a `Manifest` with the `from_file` constructor, we check for dependencies declared with either `std` or `core` packages.

If neither `core` or `std` exist, we add their associated `git` dependencies pointing to this sway repo at the `tag` equal to `forc`'s current `semver` version. This way, the implicit `core` and `std` deps are pinned alongside the version of `forc` that fetches them, guaranteeing that the manifests are compatible and that the `core` and `std` versions are compatible with eachother.

If both `core` and `std` are supplied by the user, or if only one of either `core` or `std` are provided by the user, then we don't implicitly include either. This is because in the case that only either `core` or `std` are provided, we cannot guarantee that an implicitly included `core` or `std` would be compatible with the user-specified one.

Closes #330

### Sway repo examples/tests

It's best we leave the examples and test suite with the explicit `path` dependencies in order to ensure that they remain tested against the current state of `forc` rather than the latest tagged commit. This will also avoid running into CI issues during the PRs where `forc`'s version is updated but the tag hasn't yet been pushed.

This also adds a `core` dependency declaration to all tests that otherwise contained an empty `[dependencies]` table. By overriding either the `core` or `std` dependency manually, we disable the implicit inclusion of the `std` dependency.

## TODO

- [x] Pass `forc` semver version through to `Manifest::from_file` constructor in order to set `tag` for `core` and `std` git dependencies.
- [x] Ensure build plan validation works with implicit `core`/`std`.

### CODE REVIEW

**Comment by adlerjohn** [comment]
Rather an implicitly including _both_ `core` and `std`, why not just `std`? Basically 100% of cases users will only include `std`. The only people using `core` directly should be standard library developers, and that will require local paths anyways.

**Comment by mitchmindtree** [comment]
> why not just std?

Good point! I was blindly following Rust in this case where both `core` and `std` are included, but I think Rust does this to support the `#![no_std]` use-case which isn't really relevant for Sway.

**Review by JoshuaBatty — DISMISSED** [review]
utACK.

**Comment by mitchmindtree** [comment]
Just rebased onto `master` after the merge of #1105 cc @JoshuaBatty

**Review by JoshuaBatty — APPROVED** [review]
LGTM

**Review by adlerjohn — APPROVED** [review]
LGTM, but would like @sezna to confirm that there's nothing nuanced we missed

**Review by sezna — APPROVED** [review]
Seems reasonable. Do you want to do the thing we mentioned regarding omitting std as a Forc.toml flag as a part of this PR, or as a follow-up? If the latter, would you mind making an issue to track it?

**Comment by adlerjohn** [comment]
Filed #1150 to track removing `std` from default Forc manifest

**Pull request merged**
