### PR TITLE
chore: bump to 0.63.0

### PR DESCRIPTION
**Pull request by sdankel**
## Description

To be merged after https://github.com/FuelLabs/sway/pull/6250

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by kayagokalp — APPROVED** [review]

**Comment by kayagokalp** [comment]
Should we merge it right away, or monday?

**Review by kayagokalp — CHANGES_REQUESTED** [review]
Just realized we need to wait for #6429

**Comment by JoshuaBatty** [comment]
would be nice for #6424 to land in this release.

**Review by kayagokalp — APPROVED** [review]
I think we should block until #6424 is in, otherwise we are without docs for the release 🙃 Approving to remove my RC

**Review by IGI-111 — DISMISSED** [review]

**Review by kayagokalp — APPROVED** [review]

**Review by Voxelot — APPROVED** [review]

**Pull request merged**
