### PR TITLE
Bump to v0.43.0

### PR DESCRIPTION
**Pull request by IGI-111**

### CODE REVIEW

**Review by kayagokalp — DISMISSED** [review]

**Review by Braqzen — APPROVED** [review]
Clippy is not being a bro rn

**Comment by IGI-111** [comment]
Guess we'll have to delay this anyways, there's a pretty significant bug to fix before a new release unfortunately

**Review by kayagokalp — APPROVED** [review]

**Review by Braqzen — APPROVED** [review]
Ah yes, everything is green. Just like my mental health after the FED continues to print all that extra green to decrease the amount of green required to live

**Comment by Braqzen** [comment]
Green

**Comment by Braqzen** [comment]
That's a weird looking word if you focus on it. Greeeeeeeeeen. Eeeeeen

**Pull request merged**
