### PR TITLE
Update examples and E2E tests to use master branch of std, core

### LINKED ISSUE #875: Update E2E tests to point to `master` and pin using `Forc.lock` rather than git tags
This should allow us to update the tests in the future with `forc update`, rather than manually editing the version tag.

We should also remove either `core` or `std` from each depending on which one is actually needed.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This speeds up the E2E tests quite a bit, as previously many of them
compiled two versions of `core` (e.g. `v0.0.1` as listed in
`[dependencies]`, and `master` via the `std` dependency).

Many tests have also had declared dependencies removed where unnecessary
and irrelevant to the test.

I did run into a couple issues:

- I was unable to update `b512_panic_test`, `b512_test` and
  `empty_method_initializer` as the `lo` and `hi` bits fields no longer
  appear to be accessible on the `b512` type. For now I've left these
  pinned to the old versions.
- ~The `context_testing_contract` test fails with: expected: `b256`, found:
  struct `ContractId<b256>`.~ Seems I just had to import `ContractId` and use it in the `abi`!

Closes #875.

### CODE REVIEW

**Comment by adlerjohn** [comment]
> I was unable to update b512_panic_test, b512_test and
empty_method_initializer as the lo and hi bits fields no longer
appear to be accessible on the b512 type. For now I've left these
pinned to the old versions.

cc @nfurfaro

**Comment by sezna** [comment]
^ I actually made the above change in my `if let` branch, here's a relevant diff if you'd like to copy it:

https://github.com/FuelLabs/sway/pull/815/files#diff-202cb75f9d6763cbc958f3f51e28cf2310ee1cde6b71de735b3d6512450fcb28R9

**Review by sezna — CHANGES_REQUESTED** [review]
would be cool to fix up those b512 tests

**Comment by mitchmindtree** [comment]
OK, I've rebased onto master after #859 landing and have updated the b512 and related tests - I think we're good to go!

**Review by otrho — APPROVED** [review]

**Review by emilyaherbert — APPROVED** [review]

**Review by sezna — APPROVED** [review]

**Pull request merged**
