### PR TITLE
Attempt to split up CI build steps into separate jobs

### LINKED ISSUE #772: Try splitting the existing CI "build" job into multiple jobs for a potential speedup
The CI "build" job is starting to take a while. #766 adds another 3 mins onto what was already 14 mins.

We could experiment with splitting up the various steps under the "build" job into separate jobs to allow github to run them in parallel. I'm imagining separate jobs like:

- Check crate builds
- Run crate tests
- Run e2e tests
- Check forc builds
- Check cargo fmt
- Check forc fmt

The main culprits in terms of time consumption are the builds and tests, but by splitting out the smaller steps like formatting checks it might also make it a little easier to spot what's going on when CI fails. GitHub will show the name and result of each individual *job* under the PR, which is useful in that it can save us from having to load up the failing PR's "actions" page in order to identify what went wrong.

Using multiple jobs would likely result in more compute usage overall as there may be some overlap between jobs (e.g. crate builds and crate tests), but I imagine the parallelism would get us quicker CI passes overall.

### PR DESCRIPTION
**Pull request by mitchmindtree**
Not sure if this will work just yet, but hoping this splits up the
`build` CI job to execute jobs in parallel, synchronising where
necessary using the `<job_id>.needs.<other_job_id>` feature.

Hopefully this cuts down on waiting time and makes the results a little
more readible from within the PRs.

Closes #772.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
OK after lots of fiddling around I think this might be ready review!

Apart from splitting up the `build` job into its parts, this also moves the clippy check from a separate file into the main CI workflow and adds it to the list of jobs that must be successful before publishing can go ahead.

Here's what [the workflow job graph](https://github.com/FuelLabs/sway/actions/runs/1857648109) looks like now:

Screenshot from 2022-02-17 20-01-57

The last commit took about 5mins altogether, but I think this is just because it was hitting the Rust cache for every job. When not hitting the cache, it seems to take 10-12 minutes (this is just from eyeballing the actions times [here](https://github.com/FuelLabs/sway/actions)). Either way, I think this is a bit better than the 17-20mins we've been getting when not hitting the cache with our current long sequential `build` job.

Oh yeah, I also haven't re-added this as I'm unsure what we're using it for:

```yml
      - name: Set git config
        run: |
          git config --global core.bigfilethreshold 500m
```

Do we still need it?

**Comment by Voxelot** [comment]
It looks like some job requirements are blocking this?

Screen Shot 2022-02-21 at 9 14 20 PM

**Comment by mitchmindtree** [comment]
@Voxelot I think it might only be blocked on approval:

Screenshot from 2022-02-22 16-38-42

I don't think those old CI checks need to pass, though I could be wrong!

**Comment by Voxelot** [comment]
I think it's possible to merge without CI passing, so we should probably root out why these 2 jobs are stuck?

**Comment by mitchmindtree** [comment]
I think they're not running because they're removed as a part of this PR in favour of the new jobs (this PR only touches the github workflow and doesn't touch any code). Is that what you mean?

**Comment by Voxelot** [comment]
I guess what I'm wondering is why the removed jobs are still expected. Is this because the PR isn't merged to master yet? Or is there some kind of config setting on the repo expecting these jobs?

**Review by adlerjohn — APPROVED** [review]
Fixed the repo config to not require jobs, which had the old name

**Pull request merged**
