### PR TITLE
Remove a couple unneeded uses of `CompileResult`.

### PR DESCRIPTION
**Pull request by emilyaherbert**
## Description

Small PR to remove a couple unneeded uses of `CompileResult`.

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by mohammadfawaz — DISMISSED** [review]

**Review by mitchmindtree — APPROVED** [review]
Nice, would be cool if we had a lint for unnecessary uses of our `check!` macro like this :)

**Comment by mohammadfawaz** [comment]
Ahh conflicts...

**Review by kayagokalp — APPROVED** [review]
re-approving after conflict resolution 👍 does the diff looks correct though?

**Review by mohammadfawaz — DISMISSED** [review]

**Comment by emilyaherbert** [comment]
> does the diff looks correct though?

I messed up the rebase 🤦‍♀️ Thanks for pointing this out!

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
