### PR TITLE
`forc-pkg`: Refactor `BuildPlan` construction and validation to minimize fetching, improve offline support, reduce I/O, fix bugs.

### LINKED ISSUE #1778: `BuildPlan::from_lock()` should be able to create a `BuildPlan` even there is a package removal in the manifest file
Currently `BuildPlan::from_lock()` fails when there is a package removal in the manifest file. We should be able to get some sort of an "unsafe" `BuildPlan` rather than a complete failure. Because #1686 needs to be able to generate a `diff` on the `BuildPlan` generated from the `lock` file and the updated manifest file. 

## Proposed Solution

We can do that by introducing an "unsafe" version of the `graph_to_path_map()`. Current `graph_to_path_map()` returns an error ("dependency required for path reconstruction has been removed from the manifest") when the dependency coming from the graph is not included in its parent manifest file (which is the case for the removed packages). Instead, we can point them to a default removed path (something like `$HOME/.forc/removed`). This way we can create an unsafe version of the BuildPlan which can be used to produce the diff. Once we have the diff `apply_new_manifest()` from #1686 will use that diff to create an actual BuildPlan representing the updated manifest file.

### LINKED ISSUE #1903: `forc` can create an invalid package dependency graph if the `[dependencies]` table of a `path` dependency manifest has been modified
Caught by @nfurfaro and @otrho.

## Problem

Right now we only check the immediate dependencies specified in the current project's manifest when validating the graph loaded from the lock file. This means if the `[dependencies]` table of one of the current project's `path` dependencies is modified, we don't correctly catch or account for this change when loading the graph from the lock file.

## Solution

When loading the graph from the `Forc.lock` file, we should not only validate it against the top-level project manifest, but also against the manifest of each of the path dependencies as it's possible that any of them have been modified since the `Forc.lock` file was created.

Note that this is not important for git dependencies where we know they haven't changed due to the hash.

## Temporary Workaround

Delete the `Forc.lock` and re-run `forc build` or `forc update` to allow `forc` to rebuild the graph from scratch.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This continues @kayagokalp's great work on #1974 with a wider overhaul of the package graph `BuildPlan` validation and construction.

## `BuildPlan` refactor

During kaya's work on #1974 it became clear we needed to reconsider the approach to package graph validation in order to be able to more generally account for all of the different ways a node might have been invalidated since the lock file was last written, and to be able to handle invalidated nodes in a more consistent manner.

This refactors the build plan construction process into the following distinct steps:

1. Load the project manifest.
2. Load the project lock.
3. Convert the lock to a package graph.
4. Validate the package graph, collecting all invalid nodes. A node is invalid if:
    - We are unable to construct its local path.
    - We are unable to load its manifest.
    - It is no longer present within its parent's manifest.
    - Its `Source` differs from the source or patch described in the parent's manifest.
    - Its name differs from the name within its manifest.
5. Remove all invalid nodes and any remaining nodes with no valid parents. Remaining nodes are known to be valid.
6. Fetch the missing components of the graph until it is complete. If in `offline`, only fail if we are missing a `git` node.
7. Determine the compilation order.

Closes #1903.
Closes #1778.
Makes progress on #895, #1787.

## ~`PathMap`~ `ManifestMap`

This PR also reduces the number of times that we need to read each dependency's manifest from file in order to reduce the amount of I/O performed. Each dependency's manifest should now be loaded once during either `graph_to_manifest_map` or `fetch_graph`.

This required implementing `Clone` for `ManifestFile` to allow for constructing the build plan in a manner that does not require consuming the manifest file. `ManifestFile::clone` is only ever called for the project manifest, and never for the dependencies.

As a side-effect, the `build` and `check` commands no longer require loading each package's manifest as they are already provided by the build plan. As a result both commands no longer require the sway git tag to be passed through.

### CODE REVIEW

**Review by kayagokalp — APPROVED** [review]
Looks good to me 🙌 , just left a small nit (which is not a blocker, just a simple typo).

 Also a side note I realized the build process is considerably faster (while adding a new dep) with this PR. A small benchmark on my m1 MBA:

**Adding dep before this PR:** 3.18 seconds
**Adding dep with this PR:** 0.79 seconds

**Review by kayagokalp — APPROVED** [review]

**Comment by JoshuaBatty** [comment]
I think it's fine to merge this into master and close #1974.

**Review by JoshuaBatty — APPROVED** [review]
Nice work. Looks good.

**Comment by mitchmindtree** [comment]
> Should this be merged into https://github.com/FuelLabs/sway/pull/1974 instead of master?

Ah I should have clarified this in my OP a bit further! I decided to base directly against `master` as the diff was just about as large compared to #1974 as it was to `master`, so I thought I'd try saving on the intermediary review. But you're right and I agree, in most cases it's better to base against the existing PR when possible.

**Pull request merged**
