### PR TITLE
u256: log, log2 and sqrt impl (#5329)

### LINKED ISSUE #5329: `math.sw` primitive `u256` missing trait implementations
No

- `sqrt`
- `logarithm`
- `binary logarithm`

### PR DESCRIPTION
**Pull request by sudhackar**
## Description
simple changes that borrows on `u128` implementations of `log`, `log2` and `sqrt` - only with little changes. Have added a test on `u128` too as it was missing for `log` and the output was confusing to at least me.

This should fix #5329

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by sudhackar** [comment]
ping @SwayStar123 as requested

**Comment by SwayStar123** [comment]
Thank you for the PR! But it looks like you added the functions to the wrong type. the u256 library houses the deprecated U256 type. There is now a primitive u256 type, it needs the implementation in the math library https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/math.sw

**Comment by sudhackar** [comment]
oof. my bad. Let me do that.

Should I scrub off these changes too?

**Comment by SwayStar123** [comment]
Yes please remove the changes related to the deprecated structs. As they will eventually be removed entirely, they are only preserved currently to give time for teams to migrate to the primitive type

**Pull request closed without merging**
