### PR TITLE
doc: Adding annotations support on highlight.js

### LINKED ISSUE #2740: Turn annotations into a lighter colour to deemphasize them in the Sway Book
Example: 
image
```rust
    #[storage(read, write)]
    fn receive_funds();
    #[storage(read, write)]
    fn send_funds(amount_to_send: u64, recipient_address: Address);
}
```

### PR DESCRIPTION
**Pull request by cold-briu**
## Description

resolves #2740
closes #4157

> In order to give a better highlighting I picked the "meta" scope as seen in [highlight.js docs](https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html)
> 
> The ["Mode" ](https://highlightjs.readthedocs.io/en/latest/language-guide.html) I've added provides the html class:  _hljs-meta_ however, the result is a white color for annotation (like plain text) and not a blue color as requested in the issue. 
> 
> The solution I've found for this is to add an additional css file to specify custom behavior for the desired class. I haven't added this file because I think it's out of scope.

## Checklist

- [✅ ] I have linked to any relevant issues.
- [ ?] I have commented my code, particularly in hard-to-understand areas.
- [ ?] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ?] I have added tests that prove my fix is effective or that my feature works.
- [✅] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [✅ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ?] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
Not a regex expert but I can mostly tell what is going on. From what I can tell it seems okay. I'm unsure about the "meta" naming though

**Comment by cold-briu** [comment]
> Not a regex expert but I can mostly tell what is going on. From what I can tell it seems okay. I'm unsure about the "meta" naming though

Hello there!
The naming comes from a default scope defined in the highlight js std 
Please check [scope Reference](https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html) for more information.
> meta: flags, modifiers, annotations, processing instructions, preprocessor directives, etc

**Review by Braqzen — APPROVED** [review]
utACK

**Review by mohammadfawaz — APPROVED** [review]
Tested this locally and it does seem better than what we currently have. The colour changes when you change the theme of the book but that's okay. At least the annotations show up as a single colour now.

**Comment by Flizyx** [comment]
Just chillin thru GitHub 🐧⭐

**Pull request merged**
