### PR TITLE
Update the spelling of the return register and the return length in the compiler for `asm` blocks

### PR DESCRIPTION
**Pull request by mohammadfawaz**
Simply changing `rv` to `ret` and `rl` to `retl` as per the [specs ](https://github.com/FuelLabs/fuel-specs/blob/master/specs/vm/main.md)

This:
```rust
script;

pub fn return_value() -> u64 {
    asm() {
       ret
    }
}

pub fn return_length() -> u64 {
    asm() {
       retl
    }
}

fn main() {
    let x = return_value();
    let y = return_length();
}
```
now compiles to:
```
.program:
ji   i4
noop
DATA_SECTION_OFFSET[0..32]
DATA_SECTION_OFFSET[32..64]
lw   $ds $is 1
add  $$ds $$ds $is
move $r0 $ret                 ; return value from inline asm
move $r0 $retl                ; return value from inline asm
ret  $zero                    ; fn main returns unit
.data:
```
as expected.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
@nfurfaro should I add tests for these in the `sway/test` directory? Or will your tests in https://github.com/FuelLabs/sway-lib-std/pull/61 have enough coverage?

**Comment by nfurfaro** [comment]
@mohammadfawaz I think if the other reserved registers are tested in the sway repo we should test these there as well,  butmy guess is they're not. I will definitely test the wrapper functions I'm adding which use ret and retl.

**Review by nfurfaro — DISMISSED** [review]
looks good.

**Review by nfurfaro — APPROVED** [review]
LG.

**Pull request merged**
