### PR TITLE
Change verbosity from debug -> info in forc init

### PR DESCRIPTION
**Pull request by ra0x3**
### Description
- Looks like `forc init` was using `debug` level tracing for verbosity instead of `info`
- This PR swaps `debug` for `info` and hides the verbosity behind the `command.verbose` option

### CODE REVIEW

**Review by adlerjohn — APPROVED** [review]

**Comment by adlerjohn** [comment]
Is this related to #2207?

**Comment by ra0x3** [comment]
> Is this related to #2207?

@adlerjohn 
- Yes, the description in #2207 is a bit of a misnomer (suggesting to remove the `verbose` flag). 
- The issue was the use of `debug!` as opposed to `info!` looks like

**Comment by adlerjohn** [comment]
:shipit:

**Comment by mitchmindtree** [comment]
I wonder if instead we should keep the usage of `debug!`, and have `verbose` be an alias for setting the logger to the `debug` level? That way we can still allow for configuring everything via the more flexible environment logging approach too, e.g. `RUST_LOG=debug forc <cmd>`.

**Comment by ra0x3** [comment]
@mitchmindtree 
- 🤦 You're totally right, I forgot we were passing `RUST_LOG=` to `forc` commands now. I'll push a change

**Comment by mitchmindtree** [comment]
> - But I'm thinking -- doesn't me specifying verbose supersede RUST_LOG?
>     - Meaning, even if I have no RUST_LOG shouldn't I see verbose output if verbose is specified?
>     - Or was that change to use tracing for verbosity (I forget which PR it was) a permanent change to RUST_LOG for verbosity as opposed to verbose?
>     - I guess it's fine if I have to pass RUST_LOG as a sort of verbose alias, but feels slightly unintuitive?

Yeah, I think it's fine for `--verbose` to override the log level provided by the `RUST_LOG=<level>` environment variable.

My point is more that, rather than going down a road where we have `if command.verbose { ... }` everywhere, we could potentially take advantage of the integrated `tracing` logging and have `verbose` be an alias for a more verbose level of logging (e.g. `debug` or `trace` level logging).

But I agree, the CLI argument should probably take precedence over the `RUST_LOG` environment variable.

**Comment by mohammadfawaz** [comment]
Is this ready to be merged?

**Comment by ra0x3** [comment]
@mohammadfawaz I'm OK to merge. @mitchmindtree If you prefer, can follow this up with a quick PR to change the `info!` back to `debug!`

**Comment by mitchmindtree** [comment]
Hey @ra0x3 I've opened https://github.com/FuelLabs/sway/issues/2305 to track this. I think it would be good to address this eventually, but it's certainly not particularly high priority so no stress :ok_hand:

**Pull request merged**
