### PR TITLE
Fix concurrent `forc` updates/builds with a unique `fetch_id`

### LINKED ISSUE #915: Unhandled contention over temporary git repository directory used for fetching deps/updating git deps
Spotted by @vnepveu last night!

When building two `forc` projects at the same time that happen to share the same dependency, it's possible that the temporary git repo used to update and checkout commits will be cleaned up by a separate process before the other is finished with it.

This is particularly frustrating for the `fuels-rs` crew as their tests are built using `tokio` in parallel! We managed to miss this issue, as our tests are currently run sequentially.

When running the fuels-rs tests on the `FuelLabs/fuels-rs` `repro-build-issue` branch, the error reveals itself under a variety of different git errors, each one likely different due to the directory being removed at a different being cleaned up during a different part of the git clone or checkout process:

```
---- multiple_read_calls stdout ----                                                                                                                                                           
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/multiple-read-calls/Forc.lock: No such file or directory (os error 2)                                                                                                                                                                                                           
thread 'multiple_read_calls' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'http://github.com/FuelLabs/sway-lib-core': failed to lock file '/home/mindtree/.forc/git/checkouts/tmp/core-c6e6700d83413f73/.git/config.lock' for writing: ; class=Os (2); code=Locked (-14)")', fuels-abigen-macro/tests/harness.rs:1386:90    
                                                                                                                                                                                               
---- abigen_different_structs_same_arg_name stdout ----                                                                                                                                        
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/two-structs/Forc.lock: No such file or directory (os error 2)                   
thread 'abigen_different_structs_same_arg_name' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'http://github.com/FuelLabs/sway-lib-core': failed to create locked file '/home/mindtree/.forc/git/checkouts/tmp/core-c6e6700d83413f73/.git/config.lock': File exists; class=Os (2); code=Locked (-14)")', fuels-abigen-macro/t
ests/harness.rs:1323:82                                                                                                                                                                                                                                                                                                                                                                        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                  
                                                                                                                                                                                               
---- test_large_return_data stdout ----                                                                                                                                                        
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/large-return-data/Forc.lock: No such file or directory (os error 2)                                                                                                                                                                                                             
thread 'test_large_return_data' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': failed to create locked file '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663/.git/config.lock': File exists; class=Os (2); code=Locked (-14)")', fuels-abigen-macro/tests/harness.rs
:1526:88                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                               
---- example_workflow stdout ----                                                                                                                                                              
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/contract_test/Forc.lock: No such file or directory (os error 2)                 
thread 'example_workflow' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': failed to lock file '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663/.git/config.lock' for writing: ; class=Os (2); code=Locked (-14)")', fuels-abigen-macro/tests/harness.rs:926:84       
                                                                                                                                                                                               
---- call_with_empty_return stdout ----                                                                                                                                                        
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/call_empty_return/Forc.lock: No such file or directory (os error 2)             
thread 'call_with_empty_return' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': failed to create locked file '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663/.git/config.lock': File exists; class=Os (2); code=Locked (-14)")', fuels-abigen-macro/tests/harness.rs
:1293:88                                                                                                                                                                                       
                                                                                                                                                                                               
---- test_connect_to_deployed_contract stdout ----                                                                                                                                             
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/contract_test/Forc.lock: No such file or directory (os error 2)                 
thread 'test_connect_to_deployed_contract' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663' exists and is not an empty directory; class=Invalid (3); code=Exists (-4)")', fuels-abigen-macro/tests/harness.rs:1458:8
4                                                                                                                                                                                              
                                                                                                                                                                                               
---- test_provider_node_launch_and_connect stdout ----                                                                                                                                         
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/contract_test/Forc.lock: No such file or directory (os error 2)                 
thread 'test_provider_node_launch_and_connect' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663' exists and is not an empty directory; class=Invalid (3); code=Exists (-4)")', fuels-abigen-macro/tests/harness.rs:15
66:84                                                                                                                                                                                          
                                                                                                                                                                                               
---- test_reverting_transaction stdout ----                                                                                                                                                    
  Creating a new `Forc.lock` file                                                                                                                                                                                                                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/revert_transaction_error/Forc.lock: No such file or directory (os error 2)      
thread 'test_reverting_transaction' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'http://github.com/FuelLabs/sway-lib-core': failed to create locked file '/home/mindtree/.forc/git/checkouts/tmp/core-c6e6700d83413f73/.git/objects/pack/pack_git2_bd8454fef2e5idx.lock': No such file or directory; class=Os (2)")', fuels
-abigen-macro/tests/harness.rs:1362:14                                                                                                                                                         
                                                                                                                                                                                               
---- type_safe_output_values stdout ----                                                                                                                                                       
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/contract_output_test/Forc.lock: No such file or directory (os error 2)                                                                                                                                                                                                          
thread 'type_safe_output_values' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'https://github.com/FuelLabs/sway-lib-core': failed to create locked file '/home/mindtree/.forc/git/checkouts/tmp/core-3fcca35e352aa663/.git/objects/pack/pack_git2_f8129668358bidx.lock': No such file or directory; class=Os (2)")', fuels-a
bigen-macro/tests/harness.rs:1087:91                                                                                                                                                           
                                                                                                                                                                                               
---- call_with_structs stdout ----                                                                                                                                                             
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/complex_types_contract/Forc.lock: No such file or directory (os error 2)                                                                                                                                                                                                        
thread 'call_with_structs' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'http://github.com/FuelLabs/sway-lib-core': an unknown git error occurred")', fuels-abigen-macro/tests/harness.rs:1210:14                                                                                                                           
                                                                                                                                                                                               
---- test_methods_typeless_argument stdout ----                                                                                                                                                
  Creating a new `Forc.lock` file                                                                                                                                                              
    Cause: failed to read /home/mindtree/programming/rust/fuel/fuels-rs/fuels-abigen-macro/tests/test_projects/empty-arguments/Forc.lock: No such file or directory (os error 2)               
thread 'test_methods_typeless_argument' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("failed to clone package 'core' from 'http://github.com/FuelLabs/sway-lib-core': failed to load object database in '/home/mindtree/.forc/git/checkouts/tmp/core-c6e6700d83413f73/.git/objects/'; class=Odb (9)")', fuels-abigen-macro/tests/harness.rs:1421:86
```

When forcing the tests to run sequentially with `cargo test --test-threads 1` we no longer get these git errors. We do still get a few errors, but these appear to be unrelated to `git` or `forc` and are instead related to `assert!` failing (possibly because I'm not running node?):

```
---- abigen_different_structs_same_arg_name stdout ----
  Bytecode size is 156 bytes.
Contract deployed @ e9bd36c47b5d9432dc0d93fdd40a3343fb1632567ba316f432d3d979db5548e1
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1338975177966630589`,
 right: `43`', fuels-abigen-macro/tests/harness.rs:1337:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- call_with_structs stdout ----
  Bytecode size is 208 bytes.
Contract deployed @ 8d84e52f824c4b3da2c24c776af61250048e07d70fb2c676e1c3a8b538c1d4e7
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `0`', fuels-abigen-macro/tests/harness.rs:1230:5

---- example_workflow stdout ----
  Bytecode size is 256 bytes.
Contract deployed @ 802d016d1ec98eb4563660854f9e8d1e5830464c7872596f6fdab138a6aefb37
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `0`', fuels-abigen-macro/tests/harness.rs:940:5

---- multiple_read_calls stdout ----
  Bytecode size is 184 bytes.
Contract deployed @ 7d1354020baefbba3a287e2bfacda9b163cf3cbfa7e0242abf9187b4a65a4b7f
thread 'main' panicked at 'assertion failed: stored.value == 42', fuels-abigen-macro/tests/harness.rs:1399:5

---- test_connect_to_deployed_contract stdout ----
  Bytecode size is 256 bytes.
Contract deployed @ 802d016d1ec98eb4563660854f9e8d1e5830464c7872596f6fdab138a6aefb37
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `13303765240647778304`,
 right: `21`', fuels-abigen-macro/tests/harness.rs:1469:5

---- test_provider_node_launch_and_connect stdout ----
  Bytecode size is 256 bytes.
Contract deployed @ 802d016d1ec98eb4563660854f9e8d1e5830464c7872596f6fdab138a6aefb37
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `0`', fuels-abigen-macro/tests/harness.rs:1584:5

---- type_safe_output_values stdout ----
  Bytecode size is 244 bytes.
Contract deployed @ 52875a92a19c8a7f405bd77e8c765f4c1a8a2ae9e778b9138478930351cabe28
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContractCallError("MemoryOverflow")', fuels-abigen-macro/tests/harness.rs:1104:10
```

@vnepveu you mentioned that `cargo test --test-threads 1` doesn't fix the git errors that you were encountering. Can you confirm that, and that the errors you are seeing are not these new unrelated errors? If you're still getting git errors, would you mind posting those here?

## Solution

The simplest approach might be to postfix the temporary git directory name with a unique "build ID" for the current build instance - I'm thinking this could be as simple as a hash of (the project path + the current timestamp).

This should solve the issue that `fuels-rs` are running into and reduce the chance of contention to the chance that two builds that share the same dependency start on the same nanosecond. If we were really worried about collisions still we could also hash the PID or generate a random number, but I think the less non-determinism the better for reproducibility and more consistent tests.

This approach has the added benefit of not needing to handle directory contention, and instead avoids the contention entirely.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This closes #915 by implementing the solution mentioned there.

### CODE REVIEW

**Comment by otrho** [comment]
Wouldn't it be simpler to just create a UUID rather than bother with hashing the time and path?

**Comment by mitchmindtree** [comment]
@otrho the idea was just to be a little more deterministic, e.g. a tool like nix could in theory run the build from the same timestamp and in theory reproduce the exact results... but you're right you could probably get away with a random number or UUID (I kinda mentioned this in #915). Either way, I felt that this was simple enough in that it didn't require introducing another crate or RNG source.

**Comment by adlerjohn** [comment]
One q, but how does `cargo` handle this?

**Comment by mitchmindtree** [comment]
Cargo uses a [`Filesystem` abstraction](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/flock.rs#L102-L111), where the idea is that all filesystem I/O is performed via this handle allowing it to enforce certain invariants like mutually exlusive access to certain files or directories.

Unfortunately, Rust has no effect-handling system or any way of enforcing API invariants around I/O effects, so the abstraction is more a best-effort approach and can still be pretty easily broken by a rogue `fs::write`, `fs::read_to_string`, or other `fs` or `io` call.

That said, I do think we could benefit by having something similar, especially once we start having more shared filesystem I/O beyond the temporary git repo directories. I'll open a dedicated issue for this, but for now I propose we land this in its current state if it helps @vnepveu to move ahead with the `fuels-rs` update.

**Review by JoshuaBatty — APPROVED** [review]

**Review by vnepveu — APPROVED** [review]
LGTM, ty for being so reactive!

**Pull request merged**
