### PR TITLE
Add `self.offset` to key values for empty storage struct types

### PR DESCRIPTION
**Pull request by bitzoic**
## Description

In the following struct, the `self.slot` of `StorageKey` types are identical. As a result, attempting to write to one will overwrite the other. This PR adds `self.offset` to ensure different keys. This PR closes https://github.com/FuelLabs/sway/issues/4524.

```rust
struct StructOfStorageMaps {
    foo: StorageMap<u64, u64>, 
    bar: StorageMap<u64, u64>,
}


storage {
    // Same slot
    struct_of_maps: StructOfStorageMaps = StructOfStorageMaps {
        foo: StorageMap {}, // Offset 1
        bar: StorageMap {}, // Offset 2
    },
}
```

**Note** This PR has no effect until https://github.com/FuelLabs/sway/issues/4523 is resolved.

## Checklist

- [x] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
This seems fine, I would add a test to prove the use case

**Comment by bitzoic** [comment]
> This seems fine, I would add a test to prove the use case

A test with identical keys will do nothing and is guaranteed to fail until https://github.com/FuelLabs/sway/issues/4523 is resolved. It should be added when this issue is worked on.

**Review by K1-R1 — COMMENTED** [review]
Looks good

**Comment by K1-R1** [comment]
Is the intention to wait until after https://github.com/FuelLabs/sway/issues/4523 is resolved to merge this?

**Comment by bitzoic** [comment]
> Is the intention to wait until after #4523 is resolved to merge this?

No but it doesn't seem like your approvals are allowing for the PR to be merged:

```
Review required
At least 2 approving reviews are required by reviewers with write access. 
```

**Review by Braqzen — APPROVED** [review]

**Comment by IGI-111** [comment]
Closing this in favor of #4537 there are subtle reasons why this change is not sufficient to fix the issue (namely that it would require breaking the memory representation of structs to work in a very painful way) and the required changes supersede it.

**Pull request closed without merging**
