### PR TITLE
Adds formatting for `if_else` control flow blocks

### PR DESCRIPTION
**Pull request by eureka-cpu**
Ref #2493 

This will have to change slightly if #2539 gets in first and vice versa since it adds changes to `CodeBlockContents` which they both rely on.

### CODE REVIEW

**Comment by Braqzen** [comment]
I may be misunderstanding something but it seems to me like the desired output of the test and the intermediate whitespace are duplicates. Shouldn't they be different so that a messy form gets formatted into the desired form?

**Comment by eureka-cpu** [comment]
> I may be misunderstanding something but it seems to me like the desired output of the test and the intermediate whitespace are duplicates. Shouldn't they be different so that a messy form gets formatted into the desired form?

Right you are, I was expecting to have to resolve some conflicts so I got lazy. Thanks for the catch 😄

**Comment by bingcicle** [comment]
When I test this with a sample `forc init` project and add the test code snippet into `main.sw`, the closing braces get pushed to the start of the line:

```
contract;

abi MyContract {
    fn test_function() -> bool;
}
impl MyContract for Contract {
    fn test_function() -> bool {
        if foo{
        foo();
}else if bar{
        bar();
}else {
        baz();
}
    }
}⏎       
```

Is this intended?

**Review by bingcicle — APPROVED** [review]
LGTM - tested some simple variations on a `forc init` project as well using the test code snippet too.

**Review by Braqzen — APPROVED** [review]

**Pull request merged**
