### PR TITLE
Small fixes for incorrect rebasing in 3411

### PR DESCRIPTION
**Pull request by JoshuaBatty**
Small fixes to a few things that got reverted in the language server while merging #3411 into master.

Specifically, versions were downgraded from 0.32.2 to 0.32.1. And the changes introduced in #3620 were omitted.

### CODE REVIEW

**Review by otrho — DISMISSED** [review]
Why wasn't this picked up by CI?

**Comment by JoshuaBatty** [comment]
> Why wasn't this picked up by CI?

CI is just checking that the version of `sway-lsp` is the correct version which it still was, just the dependencies that it uses were bumped down.

**Review by otrho — APPROVED** [review]

**Comment by otrho** [comment]
> > Why wasn't this picked up by CI?
> 
> CI is just checking that the version of `sway-lsp` is the correct version which it still was, just the dependencies that it uses were bumped down.

But those new errors from #3620  should have tests or something which would fail?  Is testing some of this stuff outside of an editor environment too hard?

**Comment by JoshuaBatty** [comment]
The 2 errors that were introduced `UnableToCreateFile` and `UnableToWriteFile` are just mapping errors from rusts `File::create` and `writeln!` so they are compatible with our custom `LanguageServerError` type. I think it's probably fine to not need specific tests for these error types as an error will be reported in the `did_chage` test if these fail for any reason.

**Review by mohammadfawaz — APPROVED** [review]

**Pull request merged**
