### PR TITLE
chore: bump to v0.42.1

### PR DESCRIPTION
**Pull request by kayagokalp**
## Description
Waiting for:

1. #4766
2. #4764
3. #4762 
4. #4760

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by kayagokalp** [comment]
Also added sdk-harness cargo.lock which was missing in previous releases.

**Comment by JoshuaBatty** [comment]
Should we also wait for #4771 to land?

**Comment by kayagokalp** [comment]
> Should we also wait for https://github.com/FuelLabs/sway/pull/4771 to land?

Decided to leave that to a later release if that sounds ok with you

**Review by xunilrj — APPROVED** [review]

**Review by Braqzen — APPROVED** [review]

**Comment by JoshuaBatty** [comment]
CI is failing at the same test as it was in #4722

[This change](https://github.com/FuelLabs/sway/pull/4722/commits/3392279e5e1f43c7a4680b3ea0fa790a91ccad15) seemed to fix it.

**Comment by kayagokalp** [comment]
Once #4775 is in it will fix the CI.

**Pull request merged**
