### PR TITLE
Implement initial support for source mapping

### PR DESCRIPTION
**Pull request by Dentosal**
Dumps a simple source map to a JSON file

### CODE REVIEW

**Comment by sezna** [comment]
This may change a bit when IR lands, but otherwise LGTM. @Dentosal there are some merge conflicts.

**Comment by adlerjohn** [comment]
cc @sezna for re-review

**Review by adlerjohn — COMMENTED** [review]
Merge conflicts

**Comment by Dentosal** [comment]
Blocked by https://github.com/FuelLabs/sway/pull/696

**Comment by Dentosal** [comment]
Not completely. This makes good progress towards #70, but some aspects like memory/variable watching are not available with this.

**Review by sezna — APPROVED** [review]
LGTM, good start.

**Pull request merged**
