### PR TITLE
Update in the vertical format for chained methods

### PR DESCRIPTION
**Pull request by AliJafriETH**

### CODE REVIEW

**Comment by AliJafriETH** [comment]
Hey @eureka-cpu, i've made the required changes, kindly review the pull request & hopefully merge it :))

Thank you so much for assigning this issue to me💯💯💯

**Comment by eureka-cpu** [comment]
Hey @AliJafriETH thanks for opening this PR! If you could add a test to `formatter/mod` that showcases the effectiveness of the changes I'll happily approve!

**Comment by AliJafriETH** [comment]
Hey @eureka-cpu, thanks for the update 👍
I opened another PR #3917 where i made the required changes in the `swayfmt/src/formatter/mod.rs`

**Comment by eureka-cpu** [comment]
> Hey @eureka-cpu, thanks for the update +1 I opened another PR #3917 where i made the required changes in the `swayfmt/src/formatter/mod.rs`

Now that I'm taking a closer look I think there is a misunderstanding about issue #3474 

The purpose is to add logic to `swayfmt` so that _Sway_ code blocks containing chained methods or fields will get vertical formatting if they exceed a certain length. This PR seems to just be re-formatting the Rust code we already have, hence why the `cargo fmt` check is failing. I think you can safely close this PR since the formatting was already to the standard of `rustfmt`.

**Pull request closed without merging**
