### PR TITLE
Small fix to the IR verifier

### PR DESCRIPTION
**Pull request by mohammadfawaz**
The result of the a `reduce` needs to be unwrapped first before checking its content. The `VerifyPhiInconsistentTypes` was never actually reached previously. I was seeing some inconsistent behavior while looking at https://github.com/FuelLabs/sway/issues/2876 and found this issue.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
> Some tests and examples are failing

Yeah :( converted to a draft and taking a look.

**Comment by otrho** [comment]
@vaivaswatha is in the process of removing PHIs from the IR altogether, so unless this is super urgent I'd say it's not worth fixing.

**Comment by mohammadfawaz** [comment]
> @vaivaswatha is in the process of removing PHIs from the IR altogether, so unless this is super urgent I'd say it's not worth fixing.

Yeah that's fair. I can close. But I'm worried about the type mismatch issues that showed up when I made this change. @vaivaswatha are you hitting these issues (with `unwrap` for example) in your current task?

**Comment by vaivaswatha** [comment]
> > @vaivaswatha is in the process of removing PHIs from the IR altogether, so unless this is super urgent I'd say it's not worth fixing.
> 
> Yeah that's fair. I can close. But I'm worried about the type mismatch issues that showed up when I made this change. @vaivaswatha are you hitting these issues (with `unwrap` for example or #2876) in your current task?

I agree with @otrho. This function is going to go.

Regarding the fix, it looks correct to me, so I don't think you should be hitting the type mismatch. I'd say it's worth looking into why that's happening.

If #2881 is the fix for #2876, i.e., we're going to have a `Never` type for one branch of this `if`, I'd say the solution should be, at the IR generation level, to not branch from that arm of the `if` to the merge block, thus avoiding that particular PHI argument (it isn't a predecessor at all, so it won't have a corresponding PHI argument). Does that sound reasonable?

**Comment by mohammadfawaz** [comment]
> Regarding the fix, it looks correct to me, so I don't think you should be hitting the type mismatch. I'd say it's worth looking into why that's happening.

That's happening specifically because the implementation of `unwrap` has a diverging path (a revert in a match) and so when I made the fix here, the type mismatch showed up - the current IR is indeed problematic as is. Now when lowering to assembly, the problem doesn't have any symptoms at runtime, but the IR for unwrap is currently malformed.

**Comment by vaivaswatha** [comment]
> > Regarding the fix, it looks correct to me, so I don't think you should be hitting the type mismatch. I'd say it's worth looking into why that's happening.
> 
> That's happening specifically because the implementation of `unwrap` has a diverging path (a revert in a match) and so when I made the fix here, the type mismatch showed up - the current IR is indeed problematic as is. Now when lowering to assembly, the problem doesn't have any symptoms at runtime, but the IR for unwrap is currently malformed.

At the type checker level, for the two branches of an `if`:
  - Types have to match OR at least one of them must be `Never`
  - The `Never` arm of the `if` will not have a branch out (it's an "exit block"). So no value flows from this block to the PHI of the merge block.
At the IR level,
  - Types have to strictly match. No concept of "Never". (hence the fix in *this* PR is correct).

**Comment by vaivaswatha** [comment]
> > > Regarding the fix, it looks correct to me, so I don't think you should be hitting the type mismatch. I'd say it's worth looking into why that's happening.
> > 
> > 
> > That's happening specifically because the implementation of `unwrap` has a diverging path (a revert in a match) and so when I made the fix here, the type mismatch showed up - the current IR is indeed problematic as is. Now when lowering to assembly, the problem doesn't have any symptoms at runtime, but the IR for unwrap is currently malformed.
> 
> At the type checker level, for the two branches of an `if`:
> 
> * Types have to match OR at least one of them must be `Never`
> * The `Never` arm of the `if` will not have a branch out (it's an "exit block"). So no value flows from this block to the PHI of the merge block.
> 
> At the IR level,
> 
> * Types have to strictly match. No concept of "Never". (hence the fix in _this_ PR is correct).

And to be able to detect this, we'll need a `__revert` intrinsic (we can't deep dive into the ASM to check that).

**Comment by mohammadfawaz** [comment]
Alright I think we all agree on a path forward then. Closing this for now despite the malformed IR (with no side effects luckily). Thanks!

**Pull request closed without merging**
