### PR TITLE
Use an advisory lock to co-ordinate access to git checkout repos

### LINKED ISSUE #2603: Running multiple instances of `forc` concurrently can (very occasionally) cause a git checkout race
I'm working on a project that compiles multiple sway projects concurrently spawning several forc processes.

Locally everything worked. When I first ran the CI I got the following error ([link](https://github.com/FuelLabs/fuels-rs/runs/7939488743?check_suite_focus=true)):
```
Error: Following Sway projects could not be built:
- foo_caller_contract, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/foo_caller_contract" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/foo_caller_contract"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: could not open '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/sway-core/src/ir_generation/function.rs' for writing: No such file or directory; class=Os (2)
 :
- auth_testing_abi, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/auth_testing_abi" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/auth_testing_abi"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: failed to stat '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/scripts/prism/components.json': No such file or directory; class=Os (2)
 :
- contract_output_test, Running command: '"/usr/local/bin/forc" "build" "--silent" "--output-directory" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/xtask/../assets/contract_output_test" "--path" "/home/runner/work/fuels-rs/fuels-rs/fuel-e2e-tests/sway_projects/contract_output_test"' failed with status: false.   Fetching git+https://github.com/fuellabs/sway?tag=v0.19.2#6808861389966f99887f71476918a562a9edd90e
Error: failed to stat '/home/runner/.forc/git/checkouts/std-57e47d01450577b4/6808861389966f99887f71476918a562a9edd90e/docs/src/sway-program-types/index.md': No such file or directory; class=Os (2)
```

There seems to be a race on the checked-out sway stdlib. I don't know the exact cause but [this code](https://github.com/FuelLabs/sway/blob/0929300e967425f4ef1903de7b9c3ff1efb1af7e/forc-pkg/src/pkg.rs#L1308) seems to be doing git checkouts and deletions on deterministic folder names without any inter-process-locking surrounding it.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This introduces an advisory lock around the re-usable git checkout repo directories.

Closes #2603, #3484.

Unfortunately, it's a little tricky to reliably test this from this project repository as doing so requires creating a test project with one or more `git` dependencies. We can't reliably add git dependencies (that point to external repos) to projects within this repo as the dependency would necessarily be at least one commit of forc behind, and as a result it's likely that these dependencies would break at some point in the future, e.g. next time forc makes some breaking change.

@segfault-magnet, @hal3e would you mind testing this branch in your use-case mentioned in #2603 to make sure we've covered the issue?

Edit: I've managed to test this locally by adding some long `sleep`s immediately after acquiring the lock guard, and then spinning up multiple processes of `forc` locally to build a toy project with multiple git dependencies. All appears to work fine, with each process blocking and waiting its turn for access to the checkout repo.

### CODE REVIEW

**Comment by bingcicle** [comment]
The way I was testing it was to fork both `sway` and `fuels-rs`, update `fuels-rs` to build with the concurrent flag and use my fork with the lock changes within the GitHub workflow instead. FWIW when I tested my fork it works on my machine but not on the CI, so results might differ there.

**Review by kayagokalp — DISMISSED** [review]
utACK

**Comment by bingcicle** [comment]
I went ahead and used my personal repo setups to check out your branch and tested it and it works: https://github.com/bingcicle/fuels-rs/actions/runs/3702649777/jobs/6273211503#step:8:236

**Review by bingcicle — APPROVED** [review]

**Review by JoshuaBatty — APPROVED** [review]

**Comment by hal3e** [comment]
I want to confirm that this works perfectly! Thanks a lot!!! :heart:

**Pull request merged**
