### PR TITLE
Some updates to `forc`'s README.md

### PR DESCRIPTION
**Pull request by mohammadfawaz**

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Is that plan to keep maintaining this `README.md`? Or do we want to consolidate the information into the Sway book?

**Review by adlerjohn — COMMENTED** [review]
The readme isn't being maintained, and it's being completely refactored in #1047

**Comment by mitchmindtree** [comment]
Yeah I like the idea of removing any examples from the README in favour of pointing to the book, particularly in the case that we have no automated way of testing the README.

**Comment by adlerjohn** [comment]
I think this PR can be closed in favor of the above-linked PR

**Comment by mohammadfawaz** [comment]
Yeah that's more sensible. Closing.

**Pull request closed without merging**
