### PR TITLE
Fix Lsp Symbol Rename Bug

### LINKED ISSUE #1042: Rename symbol in sway-lsp overwrites the ( char of a function
There is a bug where the `(` char is being deleted when using the Symbol Rename feature in VScode on a function.

for example, if we had the following function `foo()` , after renaming the symbol to `baz` the result is `baz)`

### PR DESCRIPTION
**Pull request by JoshuaBatty**
closes #1042

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Revert changes to lockfile pls, update in separate PR

**Review by mitchmindtree — COMMENTED** [review]
LGTM, but I might give @leviathanbeak the chance to give this a tick in case there was some reason for `make_range_end_inclusive` I'm overlooking.

Also it looks like the lock file update isn't necessary to land this right? If that's the case, are we able to remove that commit? I think the general approach for maintaining the lock file is to only update if it is strictly necessary for the PR to work (e.g. new dependencies were introduced or some critical bug was patched) or the PR itself is for a dedicated update of all dependencies. Otherwise it's a bit too easy to run into lots of unrelated conflicts between PRs.

**Comment by JoshuaBatty** [comment]
Ok cool, make sense. I'll omit the lock file in future PR's unless it is necessary for the PR to work. 

@leviathanbeak not sure why this function was once needed?

**Review by adlerjohn — COMMENTED** [review]
utACK, would like @leviathanbeak to weigh in too

**Comment by leviathanbeak** [comment]
@JoshuaBatty  I don't remember exactly for renaming, but I know for example when hovering over symbols there was a "off by 1" bug, where you would hover over the last character and you would not get anything so I added +1. 

So I probably added +1 to the rename range when I shouldn't, if this fix passes all the possible scenarios:
- requesting "rename" while hovering over the last character
- requesting "rename" while hovering over the next whitespace after the last character (and not getting anything back)

then I guess it's fine :)

**Comment by sezna** [comment]
Is this good? Seems like everybody is happy with it and it has been 7 days since last activity. cc @JoshuaBatty @adlerjohn

**Review by mitchmindtree — APPROVED** [review]

**Comment by JoshuaBatty** [comment]
> Is this good to go? Seems like everybody is happy with it and it has been 7 days since last activity. cc @JoshuaBatty @adlerjohn @mitchmindtree

Sorry, have been sick so haven't had a chance to double-check what Elvis recommended, going to do that now and finish this PR off.

**Comment by JoshuaBatty** [comment]
This should be good to go now, have double-checked it passes the scenarios that Elvis brought up.

**Review by mitchmindtree — APPROVED** [review]

**Pull request merged**
