### PR TITLE
Implement `EQ` trait for  `B512`

### PR DESCRIPTION
**Pull request by nfurfaro**
Not tracked in an issue, but needed nonetheless.
- This follows the implementation for `eq` for `Address` and `ContractId`, with the difference being the number of bytes to compare.

- Tests were added under e2e harness as this was the most logical place to test this directly.

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
I would rather this be implemented simply using a comparison of both parts, to avoid asm. A good optimizer will then be able to optimize away the extra logic.

**Comment by otrho** [comment]
What do you mean by a comparison of both parts?  That's what is happening with the `MEQ`...  until we add a `memcmp()` intrinsic there's not much else we can do..?

**Comment by adlerjohn** [comment]
Yeah it's not the worst, it's just that if we _can_ avoid inline asm then IMO we should, regardless of inefficiency, since inline asm is really hard to read, debug, and maintain.

**Comment by nfurfaro** [comment]
I'm afk so can't really check right now,  but if we already have `impl eq for b256`, we could check that `this.bytes[0] == other.bytes[0]`, and same for `bytes[1] `etc... which would avoid asm altogether.

**Review by otrho — APPROVED** [review]

**Review by sezna — APPROVED** [review]

**Pull request merged**
