### PR TITLE
Add `lex_commented` and `CommentedTokenStream` to `sway_parse`

### LINKED ISSUE #1517: `sway-parse` only lexes comments, and doesn't give spans
Blocker for handling comments in `swayfmt` v2

At some point we will need to find a way to handle comments so that we get types for `comment` & `multiline comment` as well as the spans. We'll need this if we want to have reformatting features for comments like: `wrap comments` or for reformatting `multiline comments` to normal comments.

### PR DESCRIPTION
**Pull request by mitchmindtree**
This adds a new `CommentedTokenStream` (and associated `CommentedTokenTree`, `CommentedGroup` and `Comment` types) to the `sway_parse::token` module. The aim is to allow users of `sway_parse` to collect the spans of comments, particularly useful for `sway-fmt-v2`.

`lex` is now implemented in terms of `lex_commented`, and simply strips the comments from the `CommentedTokenStream` to produce a `TokenStream`.

For now, a `Comment` just carries its `span`. We can add more detailed information (e.g. multi-line, single-line, doc, contains markdown, etc) in the future. For now the aim is to land just enough support that we can take a step towards the sway-fmt-v2 MVP replacing `sway-fmt`'s existing functionality.

A simple test has been added with a brief check for both single-line and multi-line comments.

Closes #1517 
Related #2122, #1516.

@canndrew would love your review in particular! Is this what you had in mind in your comment [here](https://github.com/FuelLabs/sway/issues/1517#issuecomment-1144449894)?

### CODE REVIEW

**Review by eureka-cpu — APPROVED** [review]
Thanks so much for this, happy to get this in 🥳

**Review by kayagokalp — DISMISSED** [review]
LGTM 🎉 but there seems to be a conflict popped up.

**Review by sezna — COMMENTED** [review]
Looks great and will certainly help with docstrings! Deferring to @canndrew for final approval.

**Comment by eureka-cpu** [comment]
v excited to have this in

**Comment by mitchmindtree** [comment]
Looking for 1 more :heavy_check_mark: @sezna @eureka-cpu @kayagokalp @canndrew

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
