### PR TITLE
refactor: add a method to check if a `Property` is a custom type

### PR DESCRIPTION
**Pull request by vnepveu**
This small PR just adds a checker method which is a cleaner interface for a check 
we do *a lot* in the ABIgen side of the SDK.

I wanted to add a `unit test` for it but I didin't see any in `lib.rs`, so I didn't go ahead.

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Is there a better way to do this than hardcoding strings?

**Comment by vnepveu** [comment]
I can go with using an hardcoded string constant, but at some point we *have* to filter that it's either an enum or a struct, and without the functions from the SDK, at the sway level I don't think we can do it without a hardcoded string somewhere

**Comment by mohammadfawaz** [comment]
Is the idea her to grab all non-copy types? Is this list maybe missing other complex types such as `tuples`, `arrays`, etc.?

**Comment by vnepveu** [comment]
The idea is just that we need to know when we need to parse the `components` of a `Property`, because we needed to "detect" the custom types that have to be mapped to native Rust types ie only `structs` and `enums`

**Review by otrho — APPROVED** [review]
OK, so you need this to flag when to go and look up another type declaration somewhere, which is only for structs and enums.  And maybe type aliases if we were to add those one day.

And the only type info you have is in string form.  So I guess this is fair enough.  The only question I have is is this definitely the best place to be asking the question, considering the lack of proper type info in the Property.

I'll approve but defer to @digorithm

**Comment by vnepveu** [comment]
I would actually even like a to make `Property` into something that carries a lot more "information" that it already does, for instance checking "in advance" that `type_field`, if it does not contain a valid primitive type, has the format `struct valid_struct_name` or `enum valid_struct_name`, and also a way to check natively if the property `is_enum` or `is_struct`. But maybe this is not a good design, I just feel like writing tests such as `prop.type_field.contains("struct ")` all the time isn't really clean.

**Comment by vnepveu** [comment]
Closing because of #1337

**Pull request closed without merging**
