### PR TITLE
Organize test directories better

### LINKED ISSUE #460: Organize tests into subdirs based on what feature is being tested.

### PR DESCRIPTION
**Pull request by nfurfaro**
This is an attempt to better organize our e2e tests.
- There are a lot of changes, but they are all either just moving or renaming things.
- I had to update all the file paths for tests and contracts in `mod.rs`, which adds visual clutter.
 - the `language` folder could be further sub-divided as well if that would be helpful.
 
As we move towards refactoring the test harness/driver, this could be improved upon. I think this also sets us up for merging the `sway-lib-std` tests with the `sway` repo tests, as it distinguishes between language tests and stdlib tests already.

Here's the gist of the directory layout:
```
└── test_programs
    ├── should_fail
    └── should_pass
        ├── language
        ├── require_contract_deployment
        ├── stdlib
        ├── test_abis
        └── test_contracts
```

close #460

### CODE REVIEW

**Review by otrho — CHANGES_REQUESTED** [review]
You've accidentally added `.DS_Store` files.  I don't mind this change overall though.

**Review by adlerjohn — COMMENTED** [review]
Is there a reason `while_loops` is not organized? I'm guessing it's from merging from `master`?

**Comment by otrho** [comment]
> Is there a reason `while_loops` is not organized? I'm guessing it's from merging from `master`?

Good catch!  How on earth did you notice that?  Superhuman code review skillz.

**Review by otrho — DISMISSED** [review]

**Review by otrho — APPROVED** [review]

**Comment by otrho** [comment]
I'm going to merge this now before more conflicts arise.

**Pull request merged**
