### PR TITLE
Support multi-span errors and warnings

### LINKED ISSUE #21: Support multi-span errors and warnings
Often, you want to display help text or render multiple spans in an error.

### PR DESCRIPTION
**Pull request by ironcev**
## Description

A new `Diagnostic` type is introduced for detail description of compile errors and warnings. The change is backward compatible. The existing `CompileWarning`s and `CompileError`s will continue render as they had before.

The `Diagnostic` is formed out of a:
- _Level_: Error or Warning.
- _Code_: Unique error or warning code. Placeholder for future. Not used at the moment.
- _Reason_: Short description of the diagnostic, not related to a specific error/warning. Answers the question "Why is this an error/warning?" E.g., Because - "Constants cannot be shadowed".
- _Issue_: Short description of the concrete case that the compiler has found. E.g., "Variable "X" shadows imported constant with the same name"
- _Hints_: Detailed description of the diagnostic placed in the source code.
- _Help_: Additional friendly information that helps understanding and solving the issue, but which is not related to a place in code.

07C Constant shadowing - Alias - After 02 - Terminology

The `Diagnostic`s are defined imperatively in code right now, pretty much the sam way we do `CompilWarning`s at the moment. Development of a proc-macro that should make de definitions declarative is out of scope of #21.

## Known Limitations

The `annotate-snippets` library has a bug and a missing functionality for which I opened issues:

- Wrong display of line numbers when using folding of lines of code. This issue is fixed but there is no patch release provided: https://github.com/rust-lang/annotate-snippets-rs/issues/52#issuecomment-1657829040
- No possibility to remove the "note:" prefix as shown on the image above: https://github.com/rust-lang/annotate-snippets-rs/issues/59

These two issues are not blocking. Proposal is to wait for the official support in the library, or contribute or in the worst case make a workaround in our code.

### Errors
07A Constant shadowing - Alias - Before

07C Constant shadowing - Alias - After 02

### Warnings
06A NonScreamingSnakeCaseConstName - Before

06B NonScreamingSnakeCaseConstName - After

Closes #21

## Checklist

- [x] I have linked to any relevant issues.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [x] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [x] I have requested a review from the relevant team or maintainers.

### CODE REVIEW

**Comment by ironcev** [comment]
There is a one _TODO-IG_ in code that I still want to do, before providing the final PR: removing the `Hint` struct introduced to explain the `IntrinsicUnsupportedArgType` error and turning this error into `Diagnostic`.

Thus, a draft PR. But this additional change does not affect the overall design. It's just another one usage example.

**Comment by ironcev** [comment]
@FuelLabs/tooling The change is backward compatible. The LSP and IDE plugins shouldn't be affected.

It would be cool though, to add the support for `Diagnostic` to LSP and IDEs and show multi-span messages and e.g. the complete compiler output of a dignostic the way Rust VS Code plugin is doing it.

Let me know if you have any questions.

In case of integration into LSP/IDE, do you want to take over from here?
If needed I can also gladly do it.

**Comment by xunilrj** [comment]
Not related to your changes. But looking at the `check` in the *.toml files, I am wondering if it is not time to consider https://github.com/mitsuhiko/insta. 

It is much easier to assess the quality of error messages with it.

**Review by xunilrj — APPROVED** [review]

**Comment by ironcev** [comment]
Defining `filecheck` tests is straightforward, but maintaining them, especially when changing error messages on a scale, is time consuming. `insta` looks promising. We snapshot the expected output and build tests around them. I see the benefit and would say it's worth investing in trying it out.

**Review by anton-trunov — APPROVED** [review]
Awesome stuff!

**Comment by anton-trunov** [comment]
@xunilrj insta indeed looks great!

**Pull request merged**
