### PR TITLE
updated the sway book reference

### PR DESCRIPTION
**Pull request by yash251**
solves #3559

### CODE REVIEW

**Review by Braqzen — CHANGES_REQUESTED** [review]
The issue specifies that we need to add the `reference` rather than replace the current `book`. Could you revert your change and add a section informing users about the `reference` and what it is?

**Comment by yash251** [comment]
How about this @Braqzen 👇🏻
## Documentation
For user documentation, including installing release builds, see the Sway Book: https://fuellabs.github.io/sway/latest/.

Also view the technical reference for the Sway programming language: https://fuellabs.github.io/sway/master/reference/

**Comment by Braqzen** [comment]
> How about this @Braqzen 👇🏻
> 
> ## Documentation
> For user documentation, including installing release builds, see the Sway Book: https://fuellabs.github.io/sway/latest/.
> 
> Also view the technical reference for the Sway programming language: https://fuellabs.github.io/sway/master/reference/

Sure, I think that looks good!

**Comment by yash251** [comment]
updated @Braqzen

**Review by Braqzen — APPROVED** [review]

**Review by sezna — APPROVED** [review]

**Pull request merged**
