### PR TITLE
Switch all `--use-ir` build config options to `--use-orig-asm`.

### LINKED ISSUE #847: Switch the default codegen pipeline to use IR.
Currently there's two pipelines, AST -> ASM and AST -> IR -> ASM, with the former as the default.

We could have a grace period where we switch the default to IR and once it's definitely stable we can remove the old one.

### PR DESCRIPTION
**Pull request by otrho**
This makes the IR pipeline the default.  The tests are all passing (for me) or to be more accurate, the `should_pass` and `should_fail` tests are passing, and the contract tests are either passing or panickng in the same manner as the original codegen.

* [x] The `lib-std` test is failing.  Might be to do with contract calls via the SDK?
* [x] The array OOB test is not giving a proper span for the error.
* [x] Need to check that the errors and warnings for the passing tests all match too.

Closes #847.

### CODE REVIEW

**Comment by mohammadfawaz** [comment]
Yeah, lib-std tests are expected to fail. We might have to disable them temporarily until we have a new SDK version with the change we need.

**Comment by adlerjohn** [comment]
Could just comment them out with a TODO and an issue. Not really a big deal during this transition.

**Comment by otrho** [comment]
Have made https://github.com/FuelLabs/fuels-rs/issues/201 to track the SDK changes needed.

**Review by mohammadfawaz — APPROVED** [review]
LGTM! Thanks.

**Review by adlerjohn — APPROVED** [review]
Can you make an issue to track re-enabling the tests once the fuels-rs issue is done?

**Comment by mohammadfawaz** [comment]
> Can you make an issue to track re-enabling the tests once the fuels-rs issue is done?

Done https://github.com/FuelLabs/sway/issues/1138

**Review by sezna — APPROVED** [review]

**Pull request merged**
