### PR TITLE
Update fuel-core to 0.19

### PR DESCRIPTION
**Pull request by Dentosal**
Updates fuel-core, fuel-vm, and other fuel-* and fuels-rs dependencies to versions corresponding to fuel-core 0.19 release.

Blocked by:
* https://github.com/FuelLabs/fuels-rs/pull/997
* https://github.com/FuelLabs/forc-wallet/pull/123

### CODE REVIEW

**Comment by Voxelot** [comment]
we should have a followup ticket to switch the std-lib over to using the new bigint opcodes @K1-R1 @IGI-111

**Comment by xunilrj** [comment]
> we should have a followup ticket to switch the std-lib over to using the new bigint opcodes @K1-R1 @IGI-111

This is being done by this PR: https://github.com/FuelLabs/sway/pull/4794

**Review by kayagokalp — APPROVED** [review]
Thanks! LGTM 🎉 

To peeps merging master into here, ci is flaky as documented [here](https://github.com/FuelLabs/sway/issues/4855). So if it fails try running it again.

**Comment by kayagokalp** [comment]
Requested review from tooling peeps but it might make sense to have someone from compiler as the second ✅

**Review by JoshuaBatty — APPROVED** [review]
Thanks for the PR. LGTM

**Pull request merged**
